"""Translate Python to C that drives CPython through its C API.

This is the third tier, and it answers a different question from the other two.
``py2bin compile`` produces machine code with no interpreter, for a subset that
has no Python object model at all - an ``int`` is a register. ``py2bin freeze``
carries an interpreter and runs the source unchanged. This one sits between
them: every value is a ``PyObject *``, every operation is a C-API call, and the
result is machine code that needs libpython to run.

That is the strategy Nuitka uses. What is different here is that nothing
outside the standard library is involved on the way: py2bin emits the C and
py2bin's own C compiler turns it into machine code, so there is no clang, no
assembler and no linker in the pipeline.

What it buys over the native tier is Python's own semantics - integers that do
not stop at 64 bits, because ``PyNumber_Add`` on two ``PyLong`` objects is the
same arbitrary-precision addition the interpreter performs.

Reference counting follows one rule, chosen because it is easy to check by
reading: **every expression yields a reference the caller owns**. Reading a
name therefore increments before handing the value back, and every value that
a statement finishes with is released. A rule that holds everywhere is worth
more here than one that saves an increment in places.
"""

from __future__ import annotations

import ast
from pathlib import Path


class CApiEmitError(SyntaxError):
    """Something in the program has no C-API translation here yet."""


#: The entry points the generated C declares for itself. Nothing includes
#: Python.h: its headers carry function-pointer typedefs and macros that this
#: project's C front end does not parse, and the declarations that are
#: genuinely needed fit in a dozen lines.
_PROTOTYPES = """\
/* Generated by py2bin: Python -> C driving the CPython C API. */
typedef struct _object PyObject;

extern void Py_Initialize(void);
extern void Py_Finalize(void);
extern PyObject *PyLong_FromLongLong(long long value);
extern long long PyLong_AsLongLong(PyObject *value);
extern PyObject *PyUnicode_FromString(const char *text);
extern PyObject *PyNumber_Add(PyObject *left, PyObject *right);
extern PyObject *PyNumber_Subtract(PyObject *left, PyObject *right);
extern PyObject *PyNumber_Multiply(PyObject *left, PyObject *right);
extern PyObject *PyNumber_TrueDivide(PyObject *left, PyObject *right);
extern PyObject *PyObject_RichCompare(PyObject *left, PyObject *right, int op);
extern int PyObject_IsTrue(PyObject *value);
extern PyObject *PyObject_Str(PyObject *value);
extern PyObject *PySys_GetObject(const char *name);
extern int PyFile_WriteObject(PyObject *value, PyObject *stream, int flags);
extern int PyFile_WriteString(const char *text, PyObject *stream);
extern void Py_IncRef(PyObject *object);
extern void Py_DecRef(PyObject *object);
extern int PyRun_SimpleString(const char *command);
extern PyObject *PyImport_ImportModule(const char *name);
extern PyObject *PyObject_GetAttrString(PyObject *object, const char *name);
extern PyObject *PyObject_CallNoArgs(PyObject *callable);
extern PyObject *PyObject_CallOneArg(PyObject *callable, PyObject *argument);
extern long long PyObject_Size(PyObject *object);
extern PyObject *PyObject_Call(PyObject *callable, PyObject *args, PyObject *kwargs);
extern PyObject *PyTuple_New(long long length);
extern int PyTuple_SetItem(PyObject *tuple, long long index, PyObject *value);
extern void PyErr_Print(void);
extern int exit(int status);
"""

#: CPython's comparison opcodes, in the order Py_LT..Py_GE.
_COMPARISONS = {
    ast.Lt: 0,
    ast.LtE: 1,
    ast.Eq: 2,
    ast.NotEq: 3,
    ast.Gt: 4,
    ast.GtE: 5,
}

_BINARY = {
    ast.Add: "PyNumber_Add",
    ast.Sub: "PyNumber_Subtract",
    ast.Mult: "PyNumber_Multiply",
    ast.Div: "PyNumber_TrueDivide",
}


def _c_string(text: str) -> str:
    """``text`` as a C string literal, escaped so the C parser reads it back."""

    out = ['"']
    for character in text:
        if character == "\\":
            out.append("\\\\")
        elif character == '"':
            out.append('\\"')
        elif character == "\n":
            out.append("\\n")
        elif character == "\t":
            out.append("\\t")
        elif " " <= character <= "~":
            out.append(character)
        else:
            # Anything outside printable ASCII goes in as its UTF-8 bytes, so
            # the literal stays ASCII and the runtime still sees the text.
            out.extend(f"\\{byte:03o}" for byte in character.encode("utf-8"))
    out.append('"')
    return "".join(out)


class _Function:
    """One Python function being written out as a C function."""

    def __init__(self, name: str, parameters: tuple[str, ...]) -> None:
        self.name = name
        self.parameters = parameters
        self.locals: list[str] = []
        self.body: list[str] = []
        self.temporaries = 0


class CApiEmitter:
    """Walk a module and write the C that drives the interpreter."""

    def __init__(self, path: Path) -> None:
        self.path = path
        self.functions: list[_Function] = []
        self.known_functions: dict[str, int] = {}
        self.current: _Function | None = None

    # --- helpers ---------------------------------------------------------

    def fail(self, node: ast.AST, message: str) -> CApiEmitError:
        line = getattr(node, "lineno", 1)
        column = getattr(node, "col_offset", 0) + 1
        return CApiEmitError(f"{self.path}:{line}:{column}: {message}")

    def emit(self, line: str, indent: int = 1) -> None:
        assert self.current is not None
        self.current.body.append("    " * indent + line)

    def checked(self, target: str, indent: int) -> str:
        """Stop if the C-API call failed.

        A C-API function answers NULL and leaves an exception set. Letting that
        NULL travel is how `1 + "x"` came to print `<NULL>` and exit 0 where
        CPython raises TypeError and exits 1. Printing the exception and
        leaving with status 1 is what the interpreter does with one nothing
        catches, and nothing here can catch one yet.
        """

        self.emit(f"if (!{target}) {{ PyErr_Print(); exit(1); }}", indent)
        return target

    def temporary(self) -> str:
        assert self.current is not None
        self.current.temporaries += 1
        name = f"_t{self.current.temporaries}"
        self.current.locals.append(name)
        return name

    def declare(self, name: str) -> str:
        """The C name for a Python local, declared on first use."""

        assert self.current is not None
        c_name = f"v_{name}"
        if c_name not in self.current.locals and name not in self.current.parameters:
            self.current.locals.append(c_name)
        return c_name

    # --- expressions -----------------------------------------------------

    def expression(self, node: ast.expr, indent: int) -> str:
        """Emit ``node`` and return a C variable owning the result."""

        if isinstance(node, ast.Constant):
            return self.constant(node, indent)
        if isinstance(node, ast.Name):
            return self.name(node, indent)
        if isinstance(node, ast.BinOp):
            return self.binary(node, indent)
        if isinstance(node, ast.Compare):
            return self.comparison(node, indent)
        if isinstance(node, ast.Attribute):
            return self.attribute(node, indent)
        if isinstance(node, ast.Call):
            return self.call(node, indent)
        raise self.fail(
            node, f"{type(node).__name__} has no C-API translation here yet"
        )

    def constant(self, node: ast.Constant, indent: int) -> str:
        target = self.temporary()
        if isinstance(node.value, bool) or node.value is None:
            raise self.fail(node, "bool and None are not translated here yet")
        if isinstance(node.value, int):
            self.emit(
                f"{target} = PyLong_FromLongLong({node.value}LL);", indent
            )
            return self.checked(target, indent)
        if isinstance(node.value, str):
            self.emit(
                f"{target} = PyUnicode_FromString({_c_string(node.value)});", indent
            )
            return self.checked(target, indent)
        raise self.fail(node, f"a {type(node.value).__name__} constant is not translated here yet")

    def name(self, node: ast.Name, indent: int) -> str:
        assert self.current is not None
        c_name = (
            f"p_{node.id}" if node.id in self.current.parameters else f"v_{node.id}"
        )
        if c_name not in self.current.locals and node.id not in self.current.parameters:
            raise self.fail(node, f"{node.id!r} is used before it is assigned")
        target = self.temporary()
        # Handed back as an owned reference, like every other expression, so a
        # caller never has to ask where a value came from before releasing it.
        self.emit(f"Py_IncRef({c_name});", indent)
        self.emit(f"{target} = {c_name};", indent)
        return target

    def binary(self, node: ast.BinOp, indent: int) -> str:
        function = _BINARY.get(type(node.op))
        if function is None:
            raise self.fail(node, f"{type(node.op).__name__} is not translated here yet")
        left = self.expression(node.left, indent)
        right = self.expression(node.right, indent)
        target = self.temporary()
        self.emit(f"{target} = {function}({left}, {right});", indent)
        self.emit(f"Py_DecRef({left});", indent)
        self.emit(f"Py_DecRef({right});", indent)
        return self.checked(target, indent)

    def comparison(self, node: ast.Compare, indent: int) -> str:
        if len(node.ops) != 1:
            raise self.fail(node, "a comparison chain is not translated here yet")
        operation = _COMPARISONS.get(type(node.ops[0]))
        if operation is None:
            raise self.fail(node, f"{type(node.ops[0]).__name__} is not translated here yet")
        left = self.expression(node.left, indent)
        right = self.expression(node.comparators[0], indent)
        target = self.temporary()
        self.emit(
            f"{target} = PyObject_RichCompare({left}, {right}, {operation});", indent
        )
        self.emit(f"Py_DecRef({left});", indent)
        self.emit(f"Py_DecRef({right});", indent)
        return self.checked(target, indent)

    def attribute(self, node: ast.Attribute, indent: int) -> str:
        value = self.expression(node.value, indent)
        target = self.temporary()
        self.emit(
            f"{target} = PyObject_GetAttrString({value}, {_c_string(node.attr)});",
            indent,
        )
        self.emit(f"Py_DecRef({value});", indent)
        return self.checked(target, indent)

    def call(self, node: ast.Call, indent: int) -> str:
        if node.keywords:
            raise self.fail(node, "keyword arguments are not translated here yet")
        if isinstance(node.func, ast.Attribute):
            return self.method_call(node, indent)
        if not isinstance(node.func, ast.Name):
            raise self.fail(node, "only a call to a named function is translated here")
        if node.func.id == "len":
            if len(node.args) != 1:
                raise self.fail(node, "len() takes one argument")
            value = self.expression(node.args[0], indent)
            target = self.temporary()
            self.emit(f"{target} = PyLong_FromLongLong(PyObject_Size({value}));", indent)
            self.emit(f"Py_DecRef({value});", indent)
            return self.checked(target, indent)
        if node.func.id == "str":
            if len(node.args) != 1:
                raise self.fail(node, "str() takes one argument")
            value = self.expression(node.args[0], indent)
            target = self.temporary()
            self.emit(f"{target} = PyObject_Str({value});", indent)
            self.emit(f"Py_DecRef({value});", indent)
            return self.checked(target, indent)
        if node.func.id not in self.known_functions:
            raise self.fail(
                node, f"{node.func.id!r} is not a function defined in this module"
            )
        expected = self.known_functions[node.func.id]
        if len(node.args) != expected:
            raise self.fail(
                node,
                f"{node.func.id}() takes {expected} argument(s), "
                f"{len(node.args)} given",
            )
        arguments = [self.expression(item, indent) for item in node.args]
        target = self.temporary()
        self.emit(f"{target} = f_{node.func.id}({', '.join(arguments)});", indent)
        for argument in arguments:
            self.emit(f"Py_DecRef({argument});", indent)
        return self.checked(target, indent)

    def method_call(self, node: ast.Call, indent: int) -> str:
        """`x.f()` and `x.f(a)` - the two arities the vetted set can call.

        More arguments need PyObject_Call and a tuple to put them in, and
        neither is in the vetted set, so they are refused by name rather than
        approximated.
        """

        assert isinstance(node.func, ast.Attribute)
        callable_value = self.attribute(node.func, indent)
        target = self.invoke(callable_value, node.args, indent)
        self.emit(f"Py_DecRef({callable_value});", indent)
        return self.checked(target, indent)

    def invoke(self, callable_value: str, args: list, indent: int) -> str:
        """Call something with any number of arguments.

        Nought and one have their own entry points; beyond that the arguments
        go into a tuple. PyTuple_SetItem *steals* the reference it is given,
        which is why nothing is released after it - releasing again would be a
        second drop of a reference this code no longer owns.
        """

        target = self.temporary()
        if not args:
            self.emit(f"{target} = PyObject_CallNoArgs({callable_value});", indent)
            return self.checked(target, indent)
        if len(args) == 1:
            argument = self.expression(args[0], indent)
            self.emit(
                f"{target} = PyObject_CallOneArg({callable_value}, {argument});", indent
            )
            self.emit(f"Py_DecRef({argument});", indent)
            return self.checked(target, indent)
        values = [self.expression(item, indent) for item in args]
        holder = self.temporary()
        self.emit(f"{holder} = PyTuple_New({len(values)}LL);", indent)
        for position, value in enumerate(values):
            self.emit(f"PyTuple_SetItem({holder}, {position}LL, {value});", indent)
        self.emit(f"{target} = PyObject_Call({callable_value}, {holder}, 0);", indent)
        self.emit(f"Py_DecRef({holder});", indent)
        return self.checked(target, indent)

    # --- statements ------------------------------------------------------

    def statement(self, node: ast.stmt, indent: int) -> None:
        if isinstance(node, ast.Assign):
            self.assignment(node, indent)
        elif isinstance(node, ast.Expr):
            self.expression_statement(node, indent)
        elif isinstance(node, ast.If):
            self.conditional(node, indent)
        elif isinstance(node, ast.While):
            self.loop(node, indent)
        elif isinstance(node, ast.Return):
            self.give_back(node, indent)
        elif isinstance(node, ast.Import):
            self.import_module(node, indent)
        elif isinstance(node, ast.Pass):
            pass
        elif isinstance(node, ast.FunctionDef):
            raise self.fail(node, "a nested function is not translated here yet")
        else:
            raise self.fail(
                node, f"{type(node).__name__} has no C-API translation here yet"
            )

    def import_module(self, node: ast.Import, indent: int) -> None:
        """`import x` - the module object, bound to a name like any value.

        This is where the tier earns its cost. The interpreter is present and
        its import machinery works, so a compiled program can reach anything
        installed beside it - which is the whole reason to pay for libpython.
        """

        for alias in node.names:
            if "." in alias.name:
                raise self.fail(node, "a dotted import is not translated here yet")
            target = self.declare(alias.asname or alias.name)
            self.emit(f"if ({target}) Py_DecRef({target});", indent)
            self.emit(
                f'{target} = PyImport_ImportModule({_c_string(alias.name)});', indent
            )
            self.checked(target, indent)

    def assignment(self, node: ast.Assign, indent: int) -> None:
        if len(node.targets) != 1 or not isinstance(node.targets[0], ast.Name):
            raise self.fail(node, "only assignment to one name is translated here")
        value = self.expression(node.value, indent)
        target = self.declare(node.targets[0].id)
        # The name may already hold something; that reference is released
        # before it is overwritten, which is what keeps a loop from growing.
        self.emit(f"if ({target}) Py_DecRef({target});", indent)
        self.emit(f"{target} = {value};", indent)

    def expression_statement(self, node: ast.Expr, indent: int) -> None:
        if (
            isinstance(node.value, ast.Call)
            and isinstance(node.value.func, ast.Name)
            and node.value.func.id == "print"
        ):
            self.write_out(node.value, indent)
            return
        value = self.expression(node.value, indent)
        self.emit(f"Py_DecRef({value});", indent)

    def write_out(self, node: ast.Call, indent: int) -> None:
        """print(...) - straight to sys.stdout through the file API."""

        if node.keywords:
            raise self.fail(node, "print() keyword arguments are not translated here")
        stream = self.temporary()
        self.emit(f'{stream} = PySys_GetObject("stdout");', indent)
        for position, argument in enumerate(node.args):
            if position:
                self.emit(f'PyFile_WriteString(" ", {stream});', indent)
            value = self.expression(argument, indent)
            # Py_PRINT_RAW is 1: str() of the object rather than its repr,
            # which is what print writes.
            self.emit(f"PyFile_WriteObject({value}, {stream}, 1);", indent)
            self.emit(f"Py_DecRef({value});", indent)
        self.emit(f'PyFile_WriteString("\\n", {stream});', indent)

    def conditional(self, node: ast.If, indent: int) -> None:
        test = self.expression(node.test, indent)
        decision = self.temporary_flag()
        self.emit(f"{decision} = PyObject_IsTrue({test});", indent)
        self.emit(f"Py_DecRef({test});", indent)
        self.emit(f"if ({decision}) {{", indent)
        for statement in node.body:
            self.statement(statement, indent + 1)
        if node.orelse:
            self.emit("} else {", indent)
            for statement in node.orelse:
                self.statement(statement, indent + 1)
        self.emit("}", indent)

    def loop(self, node: ast.While, indent: int) -> None:
        if node.orelse:
            raise self.fail(node, "a while-else is not translated here yet")
        decision = self.temporary_flag()
        self.emit("while (1) {", indent)
        test = self.expression(node.test, indent + 1)
        self.emit(f"{decision} = PyObject_IsTrue({test});", indent + 1)
        self.emit(f"Py_DecRef({test});", indent + 1)
        self.emit(f"if (!{decision}) break;", indent + 1)
        for statement in node.body:
            self.statement(statement, indent + 1)
        self.emit("}", indent)

    def temporary_flag(self) -> str:
        assert self.current is not None
        self.current.temporaries += 1
        name = f"_c{self.current.temporaries}"
        if name not in self.current.locals:
            self.current.locals.append("int " + name)
        return name

    def give_back(self, node: ast.Return, indent: int) -> None:
        if node.value is None:
            raise self.fail(node, "a bare return is not translated here yet")
        value = self.expression(node.value, indent)
        self.emit(f"return {value};", indent)

    # --- assembly --------------------------------------------------------

    def module(self, tree: ast.Module) -> str:
        for node in tree.body:
            if isinstance(node, ast.FunctionDef):
                arguments = node.args
                if (
                    node.decorator_list
                    or arguments.vararg
                    or arguments.kwarg
                    or arguments.kwonlyargs
                    or arguments.defaults
                ):
                    raise self.fail(
                        node,
                        "a decorated function, or one with defaults or "
                        "*args/**kwargs, is not translated here yet",
                    )
                self.known_functions[node.name] = len(arguments.args)

        for node in tree.body:
            if isinstance(node, ast.FunctionDef):
                self.write_function(node)

        entry = _Function("main", ())
        self.current = entry
        for node in tree.body:
            if isinstance(node, ast.FunctionDef):
                continue
            self.statement(node, 2)
        self.functions.append(entry)
        self.current = None
        return self.render()

    def write_function(self, node: ast.FunctionDef) -> None:
        parameters = tuple(argument.arg for argument in node.args.args)
        function = _Function(node.name, parameters)
        self.current = function
        for statement in node.body:
            self.statement(statement, 1)
        # A body that falls off the end has no value to give back; that is
        # None in Python, and None is not translated here yet.
        self.emit("return PyLong_FromLongLong(0LL);", 1)
        self.functions.append(function)
        self.current = None

    def render(self) -> str:
        out = [_PROTOTYPES]
        for function in self.functions:
            if function.name == "main":
                continue
            arguments = ", ".join(
                f"PyObject *p_{name}" for name in function.parameters
            ) or "void"
            out.append(f"static PyObject *f_{function.name}({arguments});")
        out.append("")
        for function in self.functions:
            if function.name == "main":
                continue
            arguments = ", ".join(
                f"PyObject *p_{name}" for name in function.parameters
            ) or "void"
            out.append(f"static PyObject *f_{function.name}({arguments}) {{")
            out.extend(self.declarations(function, 1))
            out.extend(function.body)
            out.append("}")
            out.append("")
        entry = self.functions[-1]
        out.append("int main(void) {")
        out.append("    Py_Initialize();")
        # An embedded interpreter picks its own stdout encoding, and it is not
        # always UTF-8; a program that prints text outside ASCII would stop
        # with a UnicodeEncodeError that has nothing to do with the program.
        setup = "import sys; sys.stdout.reconfigure(encoding='utf-8')"
        out.append(f"    PyRun_SimpleString({_c_string(setup)});")
        out.append("    {")
        out.extend(self.declarations(entry, 2))
        out.extend(entry.body)
        out.append("    }")
        out.append("    Py_Finalize();")
        out.append("    return 0;")
        out.append("}")
        return "\n".join(out) + "\n"

    @staticmethod
    def declarations(function: _Function, depth: int) -> list[str]:
        lines = []
        pad = "    " * depth
        for name in function.locals:
            if name.startswith("int "):
                lines.append(f"{pad}{name} = 0;")
            else:
                lines.append(f"{pad}PyObject *{name} = 0;")
        return lines


def python_to_capi_c(source: str, path: Path | str = "<string>") -> str:
    """Translate a Python module into C that drives the CPython C API."""

    return CApiEmitter(Path(path)).module(ast.parse(source))
