"""Translate Python to C that drives CPython through its C API.

This is the third tier, and it answers a different question from the other two.
``py2bin compile`` produces machine code with no interpreter, for a subset that
has no Python object model at all - an ``int`` is a register. ``py2bin freeze``
carries an interpreter and runs the source unchanged. This one sits between
them: every value is a ``PyObject *``, every operation is a C-API call, and the
result is machine code that needs libpython to run.

That is the strategy Nuitka uses. What is different here is that nothing
outside the standard library is involved on the way: py2bin emits the C and
py2bin's own C compiler turns it into machine code, so there is no clang, no
assembler and no linker in the pipeline.

What it buys over the native tier is Python's own semantics - integers that do
not stop at 64 bits, because ``PyNumber_Add`` on two ``PyLong`` objects is the
same arbitrary-precision addition the interpreter performs.

Reference counting follows one rule, chosen because it is easy to check by
reading: **every expression yields a reference the caller owns**. Reading a
name therefore increments before handing the value back, and every value that
a statement finishes with is released. A rule that holds everywhere is worth
more here than one that saves an increment in places.
"""

from __future__ import annotations

import ast
from pathlib import Path


class CApiEmitError(SyntaxError):
    """Something in the program has no C-API translation here yet."""


#: The entry points the generated C declares for itself. Nothing includes
#: Python.h: its headers carry function-pointer typedefs and macros that this
#: project's C front end does not parse, and the declarations that are
#: genuinely needed fit in a dozen lines.
_PROTOTYPES = """\
/* Generated by py2bin: Python -> C driving the CPython C API. */
typedef struct _object PyObject;

extern void Py_Initialize(void);
extern void Py_Finalize(void);
extern PyObject *PyLong_FromLongLong(long long value);
extern long long PyLong_AsLongLong(PyObject *value);
extern PyObject *PyUnicode_FromString(const char *text);
extern PyObject *PyNumber_Add(PyObject *left, PyObject *right);
extern PyObject *PyNumber_Subtract(PyObject *left, PyObject *right);
extern PyObject *PyNumber_Multiply(PyObject *left, PyObject *right);
extern PyObject *PyNumber_TrueDivide(PyObject *left, PyObject *right);
extern PyObject *PyObject_RichCompare(PyObject *left, PyObject *right, int op);
extern int PyObject_IsTrue(PyObject *value);
extern PyObject *PyObject_Str(PyObject *value);
extern PyObject *PySys_GetObject(const char *name);
extern int PyFile_WriteObject(PyObject *value, PyObject *stream, int flags);
extern int PyFile_WriteString(const char *text, PyObject *stream);
extern void Py_IncRef(PyObject *object);
extern void Py_DecRef(PyObject *object);
extern int PyRun_SimpleString(const char *command);
extern PyObject *PyImport_ImportModule(const char *name);
extern PyObject *PyObject_GetAttrString(PyObject *object, const char *name);
extern PyObject *PyObject_CallNoArgs(PyObject *callable);
extern PyObject *PyObject_CallOneArg(PyObject *callable, PyObject *argument);
extern long long PyObject_Size(PyObject *object);
extern PyObject *PyObject_Call(PyObject *callable, PyObject *args, PyObject *kwargs);
extern PyObject *PyTuple_New(long long length);
extern int PyTuple_SetItem(PyObject *tuple, long long index, PyObject *value);
extern PyObject *PyFloat_FromDouble(double value);
extern PyObject *PyNumber_Remainder(PyObject *left, PyObject *right);
extern PyObject *PyNumber_FloorDivide(PyObject *left, PyObject *right);
extern PyObject *PyNumber_Power(PyObject *base, PyObject *exp, PyObject *mod);
extern PyObject *PyDict_New(void);
extern int PyDict_SetItem(PyObject *mapping, PyObject *key, PyObject *value);
extern PyObject *PyTuple_Pack(long long length, PyObject *a, PyObject *b);
extern PyObject *PyObject_GetItem(PyObject *container, PyObject *key);
extern int PyObject_SetItem(PyObject *container, PyObject *key, PyObject *value);
extern PyObject *PyList_New(long long length);
extern int PyList_Append(PyObject *list, PyObject *value);
extern PyObject *PyObject_GetIter(PyObject *object);
extern PyObject *PyIter_Next(PyObject *iterator);
extern PyObject *PyErr_Occurred(void);
extern void PyErr_Print(void);
extern int exit(int status);
"""

#: CPython's comparison opcodes, in the order Py_LT..Py_GE.
_COMPARISONS = {
    ast.Lt: 0,
    ast.LtE: 1,
    ast.Eq: 2,
    ast.NotEq: 3,
    ast.Gt: 4,
    ast.GtE: 5,
}

_BINARY = {
    ast.Add: "PyNumber_Add",
    ast.Sub: "PyNumber_Subtract",
    ast.Mult: "PyNumber_Multiply",
    ast.Div: "PyNumber_TrueDivide",
    ast.Mod: "PyNumber_Remainder",
    ast.FloorDiv: "PyNumber_FloorDivide",
}


def _c_string(text: str) -> str:
    """``text`` as a C string literal, escaped so the C parser reads it back."""

    out = ['"']
    for character in text:
        if character == "\\":
            out.append("\\\\")
        elif character == '"':
            out.append('\\"')
        elif character == "\n":
            out.append("\\n")
        elif character == "\t":
            out.append("\\t")
        elif " " <= character <= "~":
            out.append(character)
        else:
            # Anything outside printable ASCII goes in as its UTF-8 bytes, so
            # the literal stays ASCII and the runtime still sees the text.
            out.extend(f"\\{byte:03o}" for byte in character.encode("utf-8"))
    out.append('"')
    return "".join(out)


class _Function:
    """One Python function being written out as a C function."""

    def __init__(self, name: str, parameters: tuple[str, ...]) -> None:
        self.name = name
        self.parameters = parameters
        self.locals: list[str] = []
        self.body: list[str] = []
        self.temporaries = 0


class CApiEmitter:
    """Walk a module and write the C that drives the interpreter."""

    def __init__(self, path: Path) -> None:
        self.path = path
        self.functions: list[_Function] = []
        self.known_functions: dict[str, int] = {}
        self.current: _Function | None = None

    # --- helpers ---------------------------------------------------------

    def fail(self, node: ast.AST, message: str) -> CApiEmitError:
        line = getattr(node, "lineno", 1)
        column = getattr(node, "col_offset", 0) + 1
        return CApiEmitError(f"{self.path}:{line}:{column}: {message}")

    def emit(self, line: str, indent: int = 1) -> None:
        assert self.current is not None
        self.current.body.append("    " * indent + line)

    def checked(self, target: str, indent: int) -> str:
        """Stop if the C-API call failed.

        A C-API function answers NULL and leaves an exception set. Letting that
        NULL travel is how `1 + "x"` came to print `<NULL>` and exit 0 where
        CPython raises TypeError and exits 1. Printing the exception and
        leaving with status 1 is what the interpreter does with one nothing
        catches, and nothing here can catch one yet.
        """

        self.emit(f"if (!{target}) {{ PyErr_Print(); exit(1); }}", indent)
        return target

    def temporary(self) -> str:
        assert self.current is not None
        self.current.temporaries += 1
        name = f"_t{self.current.temporaries}"
        self.current.locals.append(name)
        return name

    def declare(self, name: str) -> str:
        """The C name for a Python local, declared on first use."""

        assert self.current is not None
        c_name = f"v_{name}"
        if c_name not in self.current.locals and name not in self.current.parameters:
            self.current.locals.append(c_name)
        return c_name

    # --- expressions -----------------------------------------------------

    def expression(self, node: ast.expr, indent: int) -> str:
        """Emit ``node`` and return a C variable owning the result."""

        if isinstance(node, ast.Constant):
            return self.constant(node, indent)
        if isinstance(node, ast.Name):
            return self.name(node, indent)
        if isinstance(node, ast.BinOp):
            return self.binary(node, indent)
        if isinstance(node, ast.Compare):
            return self.comparison(node, indent)
        if isinstance(node, ast.List):
            return self.list_literal(node, indent)
        if isinstance(node, ast.Dict):
            return self.dict_literal(node, indent)
        if isinstance(node, ast.Tuple):
            return self.tuple_literal(node, indent)
        if isinstance(node, ast.Subscript):
            return self.subscript(node, indent)
        if isinstance(node, ast.UnaryOp):
            return self.unary(node, indent)
        if isinstance(node, ast.JoinedStr):
            return self.joined(node, indent)
        if isinstance(node, ast.BoolOp):
            return self.boolean(node, indent)
        if isinstance(node, ast.Attribute):
            return self.attribute(node, indent)
        if isinstance(node, ast.Call):
            return self.call(node, indent)
        raise self.fail(
            node, f"{type(node).__name__} has no C-API translation here yet"
        )

    def constant(self, node: ast.Constant, indent: int) -> str:
        target = self.temporary()
        if isinstance(node.value, bool) or node.value is None:
            # True, False and None are attributes of the builtins module, so
            # they come from the interpreter like every other builtin rather
            # than being reconstructed here.
            self.current.temporaries -= 1
            self.current.locals.remove(target)
            return self.builtin(repr(node.value), indent)
        if isinstance(node.value, float):
            self.emit(f"{target} = PyFloat_FromDouble({node.value!r});", indent)
            return self.checked(target, indent)
        if isinstance(node.value, int):
            self.emit(
                f"{target} = PyLong_FromLongLong({node.value}LL);", indent
            )
            return self.checked(target, indent)
        if isinstance(node.value, str):
            self.emit(
                f"{target} = PyUnicode_FromString({_c_string(node.value)});", indent
            )
            return self.checked(target, indent)
        raise self.fail(node, f"a {type(node.value).__name__} constant is not translated here yet")

    def name(self, node: ast.Name, indent: int) -> str:
        assert self.current is not None
        c_name = (
            f"p_{node.id}" if node.id in self.current.parameters else f"v_{node.id}"
        )
        if c_name not in self.current.locals and node.id not in self.current.parameters:
            raise self.fail(node, f"{node.id!r} is used before it is assigned")
        target = self.temporary()
        # Handed back as an owned reference, like every other expression, so a
        # caller never has to ask where a value came from before releasing it.
        self.emit(f"Py_IncRef({c_name});", indent)
        self.emit(f"{target} = {c_name};", indent)
        return target

    def binary(self, node: ast.BinOp, indent: int) -> str:
        if isinstance(node.op, ast.Pow):
            left = self.expression(node.left, indent)
            right = self.expression(node.right, indent)
            modulus = self.builtin("None", indent)
            target = self.temporary()
            self.emit(
                f"{target} = PyNumber_Power({left}, {right}, {modulus});", indent
            )
            for value in (left, right, modulus):
                self.emit(f"Py_DecRef({value});", indent)
            return self.checked(target, indent)
        function = _BINARY.get(type(node.op))
        if function is None:
            raise self.fail(node, f"{type(node.op).__name__} is not translated here yet")
        left = self.expression(node.left, indent)
        right = self.expression(node.right, indent)
        target = self.temporary()
        self.emit(f"{target} = {function}({left}, {right});", indent)
        self.emit(f"Py_DecRef({left});", indent)
        self.emit(f"Py_DecRef({right});", indent)
        return self.checked(target, indent)

    def comparison(self, node: ast.Compare, indent: int) -> str:
        if len(node.ops) != 1:
            raise self.fail(node, "a comparison chain is not translated here yet")
        operation = _COMPARISONS.get(type(node.ops[0]))
        if operation is None:
            raise self.fail(node, f"{type(node.ops[0]).__name__} is not translated here yet")
        left = self.expression(node.left, indent)
        right = self.expression(node.comparators[0], indent)
        target = self.temporary()
        self.emit(
            f"{target} = PyObject_RichCompare({left}, {right}, {operation});", indent
        )
        self.emit(f"Py_DecRef({left});", indent)
        self.emit(f"Py_DecRef({right});", indent)
        return self.checked(target, indent)

    def joined(self, node: ast.JoinedStr, indent: int) -> str:
        """An f-string: each piece rendered, then joined by concatenation.

        A format specifier is not translated - that is `format()` with its own
        mini-language, and doing half of it would be worse than saying so.
        """

        target = self.temporary()
        self.emit(f'{target} = PyUnicode_FromString("");', indent)
        self.checked(target, indent)
        for piece in node.values:
            if isinstance(piece, ast.Constant):
                rendered = self.constant(piece, indent)
            elif isinstance(piece, ast.FormattedValue):
                if piece.format_spec is not None or piece.conversion not in (-1, 115):
                    raise self.fail(
                        node,
                        "an f-string format specifier or conversion is not "
                        "translated here yet",
                    )
                value = self.expression(piece.value, indent)
                rendered = self.temporary()
                self.emit(f"{rendered} = PyObject_Str({value});", indent)
                self.emit(f"Py_DecRef({value});", indent)
                self.checked(rendered, indent)
            else:
                raise self.fail(node, "unsupported f-string piece")
            joined = self.temporary()
            self.emit(f"{joined} = PyNumber_Add({target}, {rendered});", indent)
            self.emit(f"Py_DecRef({target});", indent)
            self.emit(f"Py_DecRef({rendered});", indent)
            self.checked(joined, indent)
            target = joined
        return target

    def boolean(self, node: ast.BoolOp, indent: int) -> str:
        """`a and b` - the operand that decides, which is a value and not a
        bool: `1 and 2` is 2 in Python, and `0 or 3` is 3."""

        target = self.temporary()
        decision = self.temporary_flag()
        self.emit(f"{target} = 0;", indent)
        first = self.expression(node.values[0], indent)
        self.emit(f"{target} = {first};", indent)
        for operand in node.values[1:]:
            self.emit(f"{decision} = PyObject_IsTrue({target});", indent)
            self.emit(f"if ({decision} < 0) {{ PyErr_Print(); exit(1); }}", indent)
            # `and` goes on to the next operand when this one is true;
            # `or` goes on when it is false. Getting this the wrong way round
            # makes `0 and boom()` call boom.
            keeps = "" if isinstance(node.op, ast.And) else "!"
            # Short-circuit: the second operand is only evaluated when the
            # first does not already settle the answer.
            self.emit(f"if ({keeps}{decision}) {{", indent)
            value = self.expression(operand, indent + 1)
            self.emit(f"Py_DecRef({target});", indent + 1)
            self.emit(f"{target} = {value};", indent + 1)
            self.emit("}", indent)
        return target

    def unary(self, node: ast.UnaryOp, indent: int) -> str:
        """`-x` and `not x`. There is no PyNumber_Negative in the vetted set,
        so a negation is `0 - x`, which is the same operation."""

        if isinstance(node.op, ast.USub):
            zero = self.temporary()
            self.emit(f"{zero} = PyLong_FromLongLong(0LL);", indent)
            self.checked(zero, indent)
            value = self.expression(node.operand, indent)
            target = self.temporary()
            self.emit(f"{target} = PyNumber_Subtract({zero}, {value});", indent)
            self.emit(f"Py_DecRef({zero});", indent)
            self.emit(f"Py_DecRef({value});", indent)
            return self.checked(target, indent)
        if isinstance(node.op, ast.Not):
            value = self.expression(node.operand, indent)
            decision = self.temporary_flag()
            self.emit(f"{decision} = PyObject_IsTrue({value});", indent)
            self.emit(f"Py_DecRef({value});", indent)
            self.emit(f"if ({decision} < 0) {{ PyErr_Print(); exit(1); }}", indent)
            # A conditional expression cannot be a C-API argument here, so
            # the two names are fetched on their own branches.
            target = self.temporary()
            self.emit(f"if ({decision}) {{", indent)
            self.emit(
                f'    {target} = PyObject_GetAttrString(_py2bin_builtins, "False");',
                indent,
            )
            self.emit("} else {", indent)
            self.emit(
                f'    {target} = PyObject_GetAttrString(_py2bin_builtins, "True");',
                indent,
            )
            self.emit("}", indent)
            return self.checked(target, indent)
        raise self.fail(node, f"{type(node.op).__name__} is not translated here yet")

    def subscript(self, node: ast.Subscript, indent: int) -> str:
        """`xs[k]` - the object protocol, so a list, a dict and a string all
        work without any of them being known about here."""

        if isinstance(node.slice, ast.Slice):
            raise self.fail(node, "a slice is not translated here yet")
        container = self.expression(node.value, indent)
        key = self.expression(node.slice, indent)
        target = self.temporary()
        self.emit(f"{target} = PyObject_GetItem({container}, {key});", indent)
        self.emit(f"Py_DecRef({container});", indent)
        self.emit(f"Py_DecRef({key});", indent)
        return self.checked(target, indent)

    def list_literal(self, node: ast.List, indent: int) -> str:
        """`[a, b, c]` - an empty list, then each element appended.

        PyList_Append does *not* steal its reference, unlike PyTuple_SetItem,
        so each element is released after it goes in.
        """

        target = self.temporary()
        self.emit(f"{target} = PyList_New(0LL);", indent)
        self.checked(target, indent)
        for element in node.elts:
            value = self.expression(element, indent)
            self.emit(f"PyList_Append({target}, {value});", indent)
            self.emit(f"Py_DecRef({value});", indent)
        return target

    def dict_literal(self, node: ast.Dict, indent: int) -> str:
        """`{k: v}` - an empty dict, then each pair set into it."""

        target = self.temporary()
        self.emit(f"{target} = PyDict_New();", indent)
        self.checked(target, indent)
        for key_node, value_node in zip(node.keys, node.values):
            if key_node is None:
                raise self.fail(node, "`**` in a dict literal is not translated here")
            key = self.expression(key_node, indent)
            value = self.expression(value_node, indent)
            self.emit(f"PyDict_SetItem({target}, {key}, {value});", indent)
            # PyDict_SetItem does not steal either reference, so both go back.
            self.emit(f"Py_DecRef({key});", indent)
            self.emit(f"Py_DecRef({value});", indent)
        return target

    def tuple_literal(self, node: ast.Tuple, indent: int) -> str:
        """`(a, b)` - built through the list the vetted set can grow, then
        handed to the tuple builtin.

        PyTuple_Pack is variadic and py2bin passes no variadic arguments, so
        its vetted arity is fixed at two and cannot serve a general tuple.
        Going through `tuple(list)` costs an allocation and works for any
        length, which is the better trade here.
        """

        listed = self.list_literal(
            ast.copy_location(ast.List(elts=node.elts, ctx=ast.Load()), node), indent
        )
        maker = self.builtin("tuple", indent)
        target = self.temporary()
        self.emit(f"{target} = PyObject_CallOneArg({maker}, {listed});", indent)
        self.emit(f"Py_DecRef({maker});", indent)
        self.emit(f"Py_DecRef({listed});", indent)
        return self.checked(target, indent)

    def builtin(self, name: str, indent: int) -> str:
        """A name from the builtins module, fetched the way Python fetches it.

        `range`, `sum`, `sorted`, `abs`, `dict` - anything the interpreter
        already has. Nothing here reimplements them; the module is imported
        once at startup and this reads an attribute off it.
        """

        target = self.temporary()
        self.emit(
            f"{target} = PyObject_GetAttrString(_py2bin_builtins, "
            f"{_c_string(name)});",
            indent,
        )
        return self.checked(target, indent)

    def attribute(self, node: ast.Attribute, indent: int) -> str:
        value = self.expression(node.value, indent)
        target = self.temporary()
        self.emit(
            f"{target} = PyObject_GetAttrString({value}, {_c_string(node.attr)});",
            indent,
        )
        self.emit(f"Py_DecRef({value});", indent)
        return self.checked(target, indent)

    def call(self, node: ast.Call, indent: int) -> str:
        if node.keywords:
            raise self.fail(node, "keyword arguments are not translated here yet")
        if isinstance(node.func, ast.Attribute):
            return self.method_call(node, indent)
        if not isinstance(node.func, ast.Name):
            raise self.fail(node, "only a call to a named function is translated here")
        if node.func.id == "len":
            if len(node.args) != 1:
                raise self.fail(node, "len() takes one argument")
            value = self.expression(node.args[0], indent)
            target = self.temporary()
            self.emit(f"{target} = PyLong_FromLongLong(PyObject_Size({value}));", indent)
            self.emit(f"Py_DecRef({value});", indent)
            return self.checked(target, indent)
        if node.func.id == "str":
            if len(node.args) != 1:
                raise self.fail(node, "str() takes one argument")
            value = self.expression(node.args[0], indent)
            target = self.temporary()
            self.emit(f"{target} = PyObject_Str({value});", indent)
            self.emit(f"Py_DecRef({value});", indent)
            return self.checked(target, indent)
        if node.func.id not in self.known_functions:
            # Not one of ours, so ask the interpreter for it.
            callable_value = self.builtin(node.func.id, indent)
            target = self.invoke(callable_value, node.args, indent)
            self.emit(f"Py_DecRef({callable_value});", indent)
            return target
        expected = self.known_functions[node.func.id]
        if len(node.args) != expected:
            raise self.fail(
                node,
                f"{node.func.id}() takes {expected} argument(s), "
                f"{len(node.args)} given",
            )
        arguments = [self.expression(item, indent) for item in node.args]
        target = self.temporary()
        self.emit(f"{target} = f_{node.func.id}({', '.join(arguments)});", indent)
        for argument in arguments:
            self.emit(f"Py_DecRef({argument});", indent)
        return self.checked(target, indent)

    def method_call(self, node: ast.Call, indent: int) -> str:
        """`x.f()` and `x.f(a)` - the two arities the vetted set can call.

        More arguments need PyObject_Call and a tuple to put them in, and
        neither is in the vetted set, so they are refused by name rather than
        approximated.
        """

        assert isinstance(node.func, ast.Attribute)
        callable_value = self.attribute(node.func, indent)
        target = self.invoke(callable_value, node.args, indent)
        self.emit(f"Py_DecRef({callable_value});", indent)
        return self.checked(target, indent)

    def invoke(self, callable_value: str, args: list, indent: int) -> str:
        """Call something with any number of arguments.

        Nought and one have their own entry points; beyond that the arguments
        go into a tuple. PyTuple_SetItem *steals* the reference it is given,
        which is why nothing is released after it - releasing again would be a
        second drop of a reference this code no longer owns.
        """

        target = self.temporary()
        if not args:
            self.emit(f"{target} = PyObject_CallNoArgs({callable_value});", indent)
            return self.checked(target, indent)
        if len(args) == 1:
            argument = self.expression(args[0], indent)
            self.emit(
                f"{target} = PyObject_CallOneArg({callable_value}, {argument});", indent
            )
            self.emit(f"Py_DecRef({argument});", indent)
            return self.checked(target, indent)
        values = [self.expression(item, indent) for item in args]
        holder = self.temporary()
        self.emit(f"{holder} = PyTuple_New({len(values)}LL);", indent)
        for position, value in enumerate(values):
            self.emit(f"PyTuple_SetItem({holder}, {position}LL, {value});", indent)
        self.emit(f"{target} = PyObject_Call({callable_value}, {holder}, 0);", indent)
        self.emit(f"Py_DecRef({holder});", indent)
        return self.checked(target, indent)

    # --- statements ------------------------------------------------------

    def statement(self, node: ast.stmt, indent: int) -> None:
        if isinstance(node, ast.Assign):
            self.assignment(node, indent)
        elif isinstance(node, ast.Expr):
            self.expression_statement(node, indent)
        elif isinstance(node, ast.If):
            self.conditional(node, indent)
        elif isinstance(node, ast.While):
            self.loop(node, indent)
        elif isinstance(node, ast.For):
            self.for_loop(node, indent)
        elif isinstance(node, ast.Return):
            self.give_back(node, indent)
        elif isinstance(node, ast.Import):
            self.import_module(node, indent)
        elif isinstance(node, ast.AugAssign):
            self.augmented(node, indent)
        elif isinstance(node, ast.Break):
            self.emit("break;", indent)
        elif isinstance(node, ast.Continue):
            self.emit("continue;", indent)
        elif isinstance(node, ast.Pass):
            pass
        elif isinstance(node, ast.FunctionDef):
            raise self.fail(node, "a nested function is not translated here yet")
        else:
            raise self.fail(
                node, f"{type(node).__name__} has no C-API translation here yet"
            )

    def import_module(self, node: ast.Import, indent: int) -> None:
        """`import x` - the module object, bound to a name like any value.

        This is where the tier earns its cost. The interpreter is present and
        its import machinery works, so a compiled program can reach anything
        installed beside it - which is the whole reason to pay for libpython.
        """

        for alias in node.names:
            if "." in alias.name:
                raise self.fail(node, "a dotted import is not translated here yet")
            target = self.declare(alias.asname or alias.name)
            self.emit(f"if ({target}) Py_DecRef({target});", indent)
            self.emit(
                f'{target} = PyImport_ImportModule({_c_string(alias.name)});', indent
            )
            self.checked(target, indent)

    def assignment(self, node: ast.Assign, indent: int) -> None:
        if len(node.targets) != 1 or not isinstance(node.targets[0], ast.Name):
            raise self.fail(node, "only assignment to one name is translated here")
        value = self.expression(node.value, indent)
        target = self.declare(node.targets[0].id)
        # The name may already hold something; that reference is released
        # before it is overwritten, which is what keeps a loop from growing.
        self.emit(f"if ({target}) Py_DecRef({target});", indent)
        self.emit(f"{target} = {value};", indent)

    def augmented(self, node: ast.AugAssign, indent: int) -> None:
        """`x += 1` - the operation, then the assignment, as Python does it."""

        if not isinstance(node.target, ast.Name):
            raise self.fail(node, "only augmented assignment to a name is translated")
        rewritten = ast.copy_location(
            ast.BinOp(
                left=ast.copy_location(
                    ast.Name(id=node.target.id, ctx=ast.Load()), node
                ),
                op=node.op,
                right=node.value,
            ),
            node,
        )
        value = self.expression(rewritten, indent)
        target = self.declare(node.target.id)
        self.emit(f"if ({target}) Py_DecRef({target});", indent)
        self.emit(f"{target} = {value};", indent)

    def expression_statement(self, node: ast.Expr, indent: int) -> None:
        if (
            isinstance(node.value, ast.Call)
            and isinstance(node.value.func, ast.Name)
            and node.value.func.id == "print"
        ):
            self.write_out(node.value, indent)
            return
        value = self.expression(node.value, indent)
        self.emit(f"Py_DecRef({value});", indent)

    def write_out(self, node: ast.Call, indent: int) -> None:
        """print(...) - straight to sys.stdout through the file API."""

        if node.keywords:
            raise self.fail(node, "print() keyword arguments are not translated here")
        stream = self.temporary()
        self.emit(f'{stream} = PySys_GetObject("stdout");', indent)
        for position, argument in enumerate(node.args):
            if position:
                self.emit(f'PyFile_WriteString(" ", {stream});', indent)
            value = self.expression(argument, indent)
            # Py_PRINT_RAW is 1: str() of the object rather than its repr,
            # which is what print writes.
            self.emit(f"PyFile_WriteObject({value}, {stream}, 1);", indent)
            self.emit(f"Py_DecRef({value});", indent)
        self.emit(f'PyFile_WriteString("\\n", {stream});', indent)

    def conditional(self, node: ast.If, indent: int) -> None:
        test = self.expression(node.test, indent)
        decision = self.temporary_flag()
        self.emit(f"{decision} = PyObject_IsTrue({test});", indent)
        self.emit(f"Py_DecRef({test});", indent)
        self.emit(f"if ({decision}) {{", indent)
        for statement in node.body:
            self.statement(statement, indent + 1)
        if node.orelse:
            self.emit("} else {", indent)
            for statement in node.orelse:
                self.statement(statement, indent + 1)
        self.emit("}", indent)

    def loop(self, node: ast.While, indent: int) -> None:
        if node.orelse:
            raise self.fail(node, "a while-else is not translated here yet")
        decision = self.temporary_flag()
        self.emit("while (1) {", indent)
        test = self.expression(node.test, indent + 1)
        self.emit(f"{decision} = PyObject_IsTrue({test});", indent + 1)
        self.emit(f"Py_DecRef({test});", indent + 1)
        self.emit(f"if (!{decision}) break;", indent + 1)
        for statement in node.body:
            self.statement(statement, indent + 1)
        self.emit("}", indent)

    def for_loop(self, node: ast.For, indent: int) -> None:
        """`for x in seq:` - the iterator protocol, exactly as Python runs it.

        `range(...)`, a list, a string, a file, a generator: whatever the
        object offers, because the interpreter is the one being asked. That is
        the difference from the native tier, which has to know the shape of
        every iterable it supports.
        """

        if node.orelse:
            raise self.fail(node, "a for-else is not translated here yet")
        if not isinstance(node.target, ast.Name):
            raise self.fail(node, "a for loop binds one name here")
        sequence = self.expression(node.iter, indent)
        iterator = self.temporary()
        self.emit(f"{iterator} = PyObject_GetIter({sequence});", indent)
        self.checked(iterator, indent)
        self.emit(f"Py_DecRef({sequence});", indent)
        item = self.temporary()
        target = self.declare(node.target.id)
        self.emit("while (1) {", indent)
        self.emit(f"{item} = PyIter_Next({iterator});", indent + 1)
        # NULL means the sequence ended, or that producing the next item
        # failed. Asking whether an exception is set is what tells them apart.
        self.emit(
            f"if (!{item}) {{ if (PyErr_Occurred()) {{ PyErr_Print(); exit(1); }} break; }}",
            indent + 1,
        )
        self.emit(f"if ({target}) Py_DecRef({target});", indent + 1)
        self.emit(f"{target} = {item};", indent + 1)
        for statement in node.body:
            self.statement(statement, indent + 1)
        self.emit("}", indent)
        self.emit(f"Py_DecRef({iterator});", indent)

    def temporary_flag(self) -> str:
        assert self.current is not None
        self.current.temporaries += 1
        name = f"_c{self.current.temporaries}"
        if name not in self.current.locals:
            self.current.locals.append("int " + name)
        return name

    def give_back(self, node: ast.Return, indent: int) -> None:
        if node.value is None:
            raise self.fail(node, "a bare return is not translated here yet")
        value = self.expression(node.value, indent)
        self.emit(f"return {value};", indent)

    # --- assembly --------------------------------------------------------

    def module(self, tree: ast.Module) -> str:
        for node in tree.body:
            if isinstance(node, ast.FunctionDef):
                arguments = node.args
                if (
                    node.decorator_list
                    or arguments.vararg
                    or arguments.kwarg
                    or arguments.kwonlyargs
                    or arguments.defaults
                ):
                    raise self.fail(
                        node,
                        "a decorated function, or one with defaults or "
                        "*args/**kwargs, is not translated here yet",
                    )
                self.known_functions[node.name] = len(arguments.args)

        for node in tree.body:
            if isinstance(node, ast.FunctionDef):
                self.write_function(node)

        entry = _Function("main", ())
        self.current = entry
        for node in tree.body:
            if isinstance(node, ast.FunctionDef):
                continue
            self.statement(node, 2)
        self.functions.append(entry)
        self.current = None
        return self.render()

    def write_function(self, node: ast.FunctionDef) -> None:
        parameters = tuple(argument.arg for argument in node.args.args)
        function = _Function(node.name, parameters)
        self.current = function
        for statement in node.body:
            self.statement(statement, 1)
        # A body that falls off the end has no value to give back; that is
        # None in Python, and None is not translated here yet.
        self.emit("return PyLong_FromLongLong(0LL);", 1)
        self.functions.append(function)
        self.current = None

    def render(self) -> str:
        out = [_PROTOTYPES]
        for function in self.functions:
            if function.name == "main":
                continue
            arguments = ", ".join(
                f"PyObject *p_{name}" for name in function.parameters
            ) or "void"
            out.append(f"static PyObject *f_{function.name}({arguments});")
        out.append("")
        for function in self.functions:
            if function.name == "main":
                continue
            arguments = ", ".join(
                f"PyObject *p_{name}" for name in function.parameters
            ) or "void"
            out.append(f"static PyObject *f_{function.name}({arguments}) {{")
            out.extend(self.declarations(function, 1))
            out.extend(function.body)
            out.append("}")
            out.append("")
        entry = self.functions[-1]
        out.append("static PyObject *_py2bin_builtins = 0;")
        out.append("")
        out.append("int main(void) {")
        out.append("    Py_Initialize();")
        out.append('    _py2bin_builtins = PyImport_ImportModule("builtins");')
        out.append(
            "    if (!_py2bin_builtins) { PyErr_Print(); exit(1); }"
        )
        # An embedded interpreter picks its own stdout encoding, and it is not
        # always UTF-8; a program that prints text outside ASCII would stop
        # with a UnicodeEncodeError that has nothing to do with the program.
        setup = "import sys; sys.stdout.reconfigure(encoding='utf-8')"
        out.append(f"    PyRun_SimpleString({_c_string(setup)});")
        out.append("    {")
        out.extend(self.declarations(entry, 2))
        out.extend(entry.body)
        out.append("    }")
        out.append("    Py_Finalize();")
        out.append("    return 0;")
        out.append("}")
        return "\n".join(out) + "\n"

    @staticmethod
    def declarations(function: _Function, depth: int) -> list[str]:
        lines = []
        pad = "    " * depth
        for name in function.locals:
            if name.startswith("int "):
                lines.append(f"{pad}{name} = 0;")
            else:
                lines.append(f"{pad}PyObject *{name} = 0;")
        return lines


def python_to_capi_c(source: str, path: Path | str = "<string>") -> str:
    """Translate a Python module into C that drives the CPython C API."""

    return CApiEmitter(Path(path)).module(ast.parse(source))
