"""Translate Python to C that drives CPython through its C API.

This is the third tier, and it answers a different question from the other two.
``py2bin compile`` produces machine code with no interpreter, for a subset that
has no Python object model at all - an ``int`` is a register. ``py2bin freeze``
carries an interpreter and runs the source unchanged. This one sits between
them: every value is a ``PyObject *``, every operation is a C-API call, and the
result is machine code that needs libpython to run.

That is the strategy Nuitka uses. What is different here is that nothing
outside the standard library is involved on the way: py2bin emits the C and
py2bin's own C compiler turns it into machine code, so there is no clang, no
assembler and no linker in the pipeline.

What it buys over the native tier is Python's own semantics - integers that do
not stop at 64 bits, because ``PyNumber_Add`` on two ``PyLong`` objects is the
same arbitrary-precision addition the interpreter performs.

Reference counting follows one rule, chosen because it is easy to check by
reading: **every expression yields a reference the caller owns**. Reading a
name therefore increments before handing the value back, and every value that
a statement finishes with is released. A rule that holds everywhere is worth
more here than one that saves an increment in places.
"""

from __future__ import annotations

import ast
from pathlib import Path


class CApiEmitError(SyntaxError):
    """Something in the program has no C-API translation here yet."""


#: The entry points the generated C declares for itself. Nothing includes
#: Python.h: its headers carry function-pointer typedefs and macros that this
#: project's C front end does not parse, and the declarations that are
#: genuinely needed fit in a dozen lines.
_PROTOTYPES = """\
/* Generated by py2bin: Python -> C driving the CPython C API. */
typedef struct _object PyObject;

extern void Py_Initialize(void);
extern void Py_Finalize(void);
extern PyObject *PyLong_FromLongLong(long long value);
extern long long PyLong_AsLongLong(PyObject *value);
extern PyObject *PyUnicode_FromString(const char *text);
extern PyObject *PyNumber_Add(PyObject *left, PyObject *right);
extern PyObject *PyNumber_Subtract(PyObject *left, PyObject *right);
extern PyObject *PyNumber_Multiply(PyObject *left, PyObject *right);
extern PyObject *PyNumber_TrueDivide(PyObject *left, PyObject *right);
extern PyObject *PyObject_RichCompare(PyObject *left, PyObject *right, int op);
extern int PyObject_IsTrue(PyObject *value);
extern PyObject *PyObject_Str(PyObject *value);
extern PyObject *PySys_GetObject(const char *name);
extern int PyFile_WriteObject(PyObject *value, PyObject *stream, int flags);
extern int PyFile_WriteString(const char *text, PyObject *stream);
extern void Py_IncRef(PyObject *object);
extern void Py_DecRef(PyObject *object);
extern int PyRun_SimpleString(const char *command);
extern PyObject *PyImport_ImportModule(const char *name);
extern PyObject *PyObject_GetAttrString(PyObject *object, const char *name);
extern PyObject *PyObject_CallNoArgs(PyObject *callable);
extern PyObject *PyObject_CallOneArg(PyObject *callable, PyObject *argument);
extern long long PyObject_Size(PyObject *object);
extern PyObject *PyObject_Call(PyObject *callable, PyObject *args, PyObject *kwargs);
extern PyObject *PyTuple_New(long long length);
extern int PyTuple_SetItem(PyObject *tuple, long long index, PyObject *value);
extern PyObject *PyFloat_FromDouble(double value);
extern PyObject *PyNumber_Remainder(PyObject *left, PyObject *right);
extern PyObject *PyNumber_Or(PyObject *left, PyObject *right);
extern PyObject *PyNumber_And(PyObject *left, PyObject *right);
extern PyObject *PyNumber_Xor(PyObject *left, PyObject *right);
extern PyObject *PyNumber_Lshift(PyObject *left, PyObject *right);
extern PyObject *PyNumber_Rshift(PyObject *left, PyObject *right);
extern int PyObject_DelItem(PyObject *container, PyObject *key);
extern PyObject *PyNumber_FloorDivide(PyObject *left, PyObject *right);
extern PyObject *PyNumber_Power(PyObject *base, PyObject *exp, PyObject *mod);
extern PyObject *PyDict_New(void);
extern int PyDict_SetItem(PyObject *mapping, PyObject *key, PyObject *value);
extern PyObject *PyTuple_Pack(long long length, PyObject *a, PyObject *b);
extern int PySequence_Contains(PyObject *container, PyObject *value);
extern int PyErr_ExceptionMatches(PyObject *exception);
extern void PyErr_SetObject(PyObject *exception, PyObject *value);
extern PyObject *PySlice_New(PyObject *start, PyObject *stop, PyObject *step);
extern void PyErr_Clear(void);
extern PyObject *PyErr_GetRaisedException(void);
extern PyObject *PyObject_GetItem(PyObject *container, PyObject *key);
extern int PyObject_SetItem(PyObject *container, PyObject *key, PyObject *value);
extern PyObject *PyList_New(long long length);
extern int PyList_Append(PyObject *list, PyObject *value);
extern PyObject *PyObject_GetIter(PyObject *object);
extern PyObject *PyIter_Next(PyObject *iterator);
extern PyObject *PyErr_Occurred(void);
extern void PyErr_Print(void);
extern int exit(int status);
"""

#: CPython's comparison opcodes, in the order Py_LT..Py_GE.
_COMPARISONS = {
    ast.Lt: 0,
    ast.LtE: 1,
    ast.Eq: 2,
    ast.NotEq: 3,
    ast.Gt: 4,
    ast.GtE: 5,
}

_BINARY = {
    ast.BitOr: "PyNumber_Or",
    ast.BitAnd: "PyNumber_And",
    ast.BitXor: "PyNumber_Xor",
    ast.LShift: "PyNumber_Lshift",
    ast.RShift: "PyNumber_Rshift",
    ast.Add: "PyNumber_Add",
    ast.Sub: "PyNumber_Subtract",
    ast.Mult: "PyNumber_Multiply",
    ast.Div: "PyNumber_TrueDivide",
    ast.Mod: "PyNumber_Remainder",
    ast.FloorDiv: "PyNumber_FloorDivide",
}


def _c_string(text: str) -> str:
    """``text`` as a C string literal, escaped so the C parser reads it back."""

    out = ['"']
    for character in text:
        if character == "\\":
            out.append("\\\\")
        elif character == '"':
            out.append('\\"')
        elif character == "\n":
            out.append("\\n")
        elif character == "\t":
            out.append("\\t")
        elif " " <= character <= "~":
            out.append(character)
        else:
            # Anything outside printable ASCII goes in as its UTF-8 bytes, so
            # the literal stays ASCII and the runtime still sees the text.
            out.extend(f"\\{byte:03o}" for byte in character.encode("utf-8"))
    out.append('"')
    return "".join(out)


class _Function:
    """One Python function being written out as a C function."""

    def __init__(
        self, name: str, parameters: tuple[str, ...], defaults: int = 0
    ) -> None:
        self.name = name
        self.parameters = parameters
        #: How many trailing parameters have defaults. A call that leaves one
        #: out passes NULL and the body fills it in.
        self.defaults = defaults
        self.locals: list[str] = []
        self.body: list[str] = []
        self.temporaries = 0


class CApiEmitter:
    """Walk a module and write the C that drives the interpreter."""

    def __init__(self, path: Path) -> None:
        self.path = path
        self.functions: list[_Function] = []
        self.known_functions: dict[str, int] = {}
        self.current: _Function | None = None
        #: Names bound at module level. They become file-scope statics so a
        #: function body can see them, which is what a Python global is.
        self.globals: set[str] = set()
        #: True while the module body itself is being written.
        self.at_module_level = False
        #: The label a failing C-API call jumps to. Empty outside a `try`,
        #: where a failure ends the process instead.
        self.handlers: list[str] = []

    # --- helpers ---------------------------------------------------------

    def fail(self, node: ast.AST, message: str) -> CApiEmitError:
        line = getattr(node, "lineno", 1)
        column = getattr(node, "col_offset", 0) + 1
        return CApiEmitError(f"{self.path}:{line}:{column}: {message}")

    def emit(self, line: str, indent: int = 1) -> None:
        assert self.current is not None
        self.current.body.append("    " * indent + line)

    def checked(self, target: str, indent: int) -> str:
        """Stop if the C-API call failed.

        A C-API function answers NULL and leaves an exception set. Letting that
        NULL travel is how `1 + "x"` came to print `<NULL>` and exit 0 where
        CPython raises TypeError and exits 1. Printing the exception and
        leaving with status 1 is what the interpreter does with one nothing
        catches, and nothing here can catch one yet.
        """

        if self.handlers:
            # Inside a `try`, a failure is the handler's business rather than
            # the end of the process.
            self.emit(f"if (!{target}) goto {self.handlers[-1]};", indent)
        else:
            self.emit(f"if (!{target}) {{ PyErr_Print(); exit(1); }}", indent)
        return target

    def temporary(self) -> str:
        assert self.current is not None
        self.current.temporaries += 1
        name = f"_t{self.current.temporaries}"
        self.current.locals.append(name)
        return name

    def declare(self, name: str) -> str:
        """The C name for a Python local, declared on first use.

        A parameter that the body assigns to is the same storage, not a new
        local - Python rebinds the parameter. The body owns its parameters
        (they are incremented on entry), so overwriting one releases what it
        held exactly as overwriting any other name does.
        """

        assert self.current is not None
        if name in self.current.parameters:
            return f"p_{name}"
        if self.at_module_level:
            # The module body's names are the program's globals, so they live
            # at file scope where a function can reach them.
            self.globals.add(name)
            return f"g_{name}"
        c_name = f"v_{name}"
        if c_name not in self.current.locals:
            self.current.locals.append(c_name)
        return c_name

    # --- expressions -----------------------------------------------------

    def expression(self, node: ast.expr, indent: int) -> str:
        """Emit ``node`` and return a C variable owning the result."""

        if isinstance(node, ast.Constant):
            return self.constant(node, indent)
        if isinstance(node, ast.Name):
            return self.name(node, indent)
        if isinstance(node, ast.BinOp):
            return self.binary(node, indent)
        if isinstance(node, ast.Compare):
            return self.comparison(node, indent)
        if isinstance(node, ast.List):
            return self.list_literal(node, indent)
        if isinstance(node, ast.Dict):
            return self.dict_literal(node, indent)
        if isinstance(node, ast.Set):
            return self.set_literal(node, indent)
        if isinstance(node, (ast.ListComp, ast.GeneratorExp, ast.SetComp)):
            return self.comprehension(node, indent)
        if isinstance(node, ast.Tuple):
            return self.tuple_literal(node, indent)
        if isinstance(node, ast.Subscript):
            return self.subscript(node, indent)
        if isinstance(node, ast.UnaryOp):
            return self.unary(node, indent)
        if isinstance(node, ast.IfExp):
            return self.conditional_expression(node, indent)
        if isinstance(node, ast.JoinedStr):
            return self.joined(node, indent)
        if isinstance(node, ast.BoolOp):
            return self.boolean(node, indent)
        if isinstance(node, ast.Attribute):
            return self.attribute(node, indent)
        if isinstance(node, ast.Call):
            return self.call(node, indent)
        raise self.fail(
            node, f"{type(node).__name__} has no C-API translation here yet"
        )

    def constant(self, node: ast.Constant, indent: int) -> str:
        target = self.temporary()
        if isinstance(node.value, bool) or node.value is None:
            # True, False and None are attributes of the builtins module, so
            # they come from the interpreter like every other builtin rather
            # than being reconstructed here.
            self.current.temporaries -= 1
            self.current.locals.remove(target)
            return self.builtin(repr(node.value), indent)
        if isinstance(node.value, float):
            self.emit(f"{target} = PyFloat_FromDouble({node.value!r});", indent)
            return self.checked(target, indent)
        if isinstance(node.value, int):
            self.emit(
                f"{target} = PyLong_FromLongLong({node.value}LL);", indent
            )
            return self.checked(target, indent)
        if isinstance(node.value, str):
            self.emit(
                f"{target} = PyUnicode_FromString({_c_string(node.value)});", indent
            )
            return self.checked(target, indent)
        raise self.fail(node, f"a {type(node.value).__name__} constant is not translated here yet")

    def reference(self, name: str) -> str | None:
        """The C name a Python name reads from, or None if nothing binds it.

        Local first, then parameter, then module global - the order Python
        looks in, minus the closures this does not have.
        """

        assert self.current is not None
        if name in self.current.parameters:
            return f"p_{name}"
        if f"v_{name}" in self.current.locals:
            return f"v_{name}"
        if name in self.globals:
            return f"g_{name}"
        return None

    def name(self, node: ast.Name, indent: int) -> str:
        assert self.current is not None
        c_name = self.reference(node.id)
        if c_name is None:
            # Local, then global, then builtins - the order Python looks in.
            # `bytes` and `len` are names as much as they are callables, and a
            # program may pass one around rather than call it.
            return self.builtin(node.id, indent)
        target = self.temporary()
        # Handed back as an owned reference, like every other expression, so a
        # caller never has to ask where a value came from before releasing it.
        self.emit(f"Py_IncRef({c_name});", indent)
        self.emit(f"{target} = {c_name};", indent)
        return target

    def binary(self, node: ast.BinOp, indent: int) -> str:
        if isinstance(node.op, ast.Pow):
            left = self.expression(node.left, indent)
            right = self.expression(node.right, indent)
            modulus = self.builtin("None", indent)
            target = self.temporary()
            self.emit(
                f"{target} = PyNumber_Power({left}, {right}, {modulus});", indent
            )
            for value in (left, right, modulus):
                self.emit(f"Py_DecRef({value});", indent)
            return self.checked(target, indent)
        function = _BINARY.get(type(node.op))
        if function is None:
            raise self.fail(node, f"{type(node.op).__name__} is not translated here yet")
        left = self.expression(node.left, indent)
        right = self.expression(node.right, indent)
        target = self.temporary()
        self.emit(f"{target} = {function}({left}, {right});", indent)
        self.emit(f"Py_DecRef({left});", indent)
        self.emit(f"Py_DecRef({right});", indent)
        return self.checked(target, indent)

    def comparison(self, node: ast.Compare, indent: int) -> str:
        if len(node.ops) != 1:
            raise self.fail(node, "a comparison chain is not translated here yet")
        if isinstance(node.ops[0], (ast.In, ast.NotIn)):
            return self.membership(node, indent)
        if isinstance(node.ops[0], (ast.Is, ast.IsNot)):
            return self.identity(node, indent)
        operation = _COMPARISONS.get(type(node.ops[0]))
        if operation is None:
            raise self.fail(node, f"{type(node.ops[0]).__name__} is not translated here yet")
        left = self.expression(node.left, indent)
        right = self.expression(node.comparators[0], indent)
        target = self.temporary()
        self.emit(
            f"{target} = PyObject_RichCompare({left}, {right}, {operation});", indent
        )
        self.emit(f"Py_DecRef({left});", indent)
        self.emit(f"Py_DecRef({right});", indent)
        return self.checked(target, indent)

    def conditional_expression(self, node: ast.IfExp, indent: int) -> str:
        """`a if c else b` - a real branch, so only one arm is evaluated."""

        decision = self.temporary_flag()
        test = self.expression(node.test, indent)
        self.emit(f"{decision} = PyObject_IsTrue({test});", indent)
        self.emit(f"Py_DecRef({test});", indent)
        self.emit(f"if ({decision} < 0) {{ PyErr_Print(); exit(1); }}", indent)
        target = self.temporary()
        self.emit(f"if ({decision}) {{", indent)
        taken = self.expression(node.body, indent + 1)
        self.emit(f"    {target} = {taken};", indent)
        self.emit("} else {", indent)
        other = self.expression(node.orelse, indent + 1)
        self.emit(f"    {target} = {other};", indent)
        self.emit("}", indent)
        return target

    def joined(self, node: ast.JoinedStr, indent: int) -> str:
        """An f-string: each piece rendered, then joined by concatenation.

        A format specifier is not translated - that is `format()` with its own
        mini-language, and doing half of it would be worse than saying so.
        """

        target = self.temporary()
        self.emit(f'{target} = PyUnicode_FromString("");', indent)
        self.checked(target, indent)
        for piece in node.values:
            if isinstance(piece, ast.Constant):
                rendered = self.constant(piece, indent)
            elif isinstance(piece, ast.FormattedValue):
                if piece.format_spec is not None or piece.conversion not in (-1, 115):
                    raise self.fail(
                        node,
                        "an f-string format specifier or conversion is not "
                        "translated here yet",
                    )
                value = self.expression(piece.value, indent)
                rendered = self.temporary()
                self.emit(f"{rendered} = PyObject_Str({value});", indent)
                self.emit(f"Py_DecRef({value});", indent)
                self.checked(rendered, indent)
            else:
                raise self.fail(node, "unsupported f-string piece")
            joined = self.temporary()
            self.emit(f"{joined} = PyNumber_Add({target}, {rendered});", indent)
            self.emit(f"Py_DecRef({target});", indent)
            self.emit(f"Py_DecRef({rendered});", indent)
            self.checked(joined, indent)
            target = joined
        return target

    def boolean(self, node: ast.BoolOp, indent: int) -> str:
        """`a and b` - the operand that decides, which is a value and not a
        bool: `1 and 2` is 2 in Python, and `0 or 3` is 3."""

        target = self.temporary()
        decision = self.temporary_flag()
        self.emit(f"{target} = 0;", indent)
        first = self.expression(node.values[0], indent)
        self.emit(f"{target} = {first};", indent)
        for operand in node.values[1:]:
            self.emit(f"{decision} = PyObject_IsTrue({target});", indent)
            self.emit(f"if ({decision} < 0) {{ PyErr_Print(); exit(1); }}", indent)
            # `and` goes on to the next operand when this one is true;
            # `or` goes on when it is false. Getting this the wrong way round
            # makes `0 and boom()` call boom.
            keeps = "" if isinstance(node.op, ast.And) else "!"
            # Short-circuit: the second operand is only evaluated when the
            # first does not already settle the answer.
            self.emit(f"if ({keeps}{decision}) {{", indent)
            value = self.expression(operand, indent + 1)
            self.emit(f"Py_DecRef({target});", indent + 1)
            self.emit(f"{target} = {value};", indent + 1)
            self.emit("}", indent)
        return target

    def unary(self, node: ast.UnaryOp, indent: int) -> str:
        """`-x` and `not x`. There is no PyNumber_Negative in the vetted set,
        so a negation is `0 - x`, which is the same operation."""

        if isinstance(node.op, ast.USub):
            zero = self.temporary()
            self.emit(f"{zero} = PyLong_FromLongLong(0LL);", indent)
            self.checked(zero, indent)
            value = self.expression(node.operand, indent)
            target = self.temporary()
            self.emit(f"{target} = PyNumber_Subtract({zero}, {value});", indent)
            self.emit(f"Py_DecRef({zero});", indent)
            self.emit(f"Py_DecRef({value});", indent)
            return self.checked(target, indent)
        if isinstance(node.op, ast.Not):
            value = self.expression(node.operand, indent)
            decision = self.temporary_flag()
            self.emit(f"{decision} = PyObject_IsTrue({value});", indent)
            self.emit(f"Py_DecRef({value});", indent)
            self.emit(f"if ({decision} < 0) {{ PyErr_Print(); exit(1); }}", indent)
            # A conditional expression cannot be a C-API argument here, so
            # the two names are fetched on their own branches.
            target = self.temporary()
            self.emit(f"if ({decision}) {{", indent)
            self.emit(
                f'    {target} = PyObject_GetAttrString(_py2bin_builtins, "False");',
                indent,
            )
            self.emit("} else {", indent)
            self.emit(
                f'    {target} = PyObject_GetAttrString(_py2bin_builtins, "True");',
                indent,
            )
            self.emit("}", indent)
            return self.checked(target, indent)
        raise self.fail(node, f"{type(node.op).__name__} is not translated here yet")

    def subscript(self, node: ast.Subscript, indent: int) -> str:
        """`xs[k]` - the object protocol, so a list, a dict and a string all
        work without any of them being known about here."""

        container = self.expression(node.value, indent)
        key = (
            self.slice_object(node.slice, indent)
            if isinstance(node.slice, ast.Slice)
            else self.expression(node.slice, indent)
        )
        target = self.temporary()
        self.emit(f"{target} = PyObject_GetItem({container}, {key});", indent)
        self.emit(f"Py_DecRef({container});", indent)
        self.emit(f"Py_DecRef({key});", indent)
        return self.checked(target, indent)

    def slice_object(self, node: ast.Slice, indent: int) -> str:
        """`a:b:c` as the slice object the subscript protocol expects."""

        parts = []
        for piece in (node.lower, node.upper, node.step):
            parts.append(
                self.builtin("None", indent)
                if piece is None
                else self.expression(piece, indent)
            )
        target = self.temporary()
        self.emit(
            f"{target} = PySlice_New({parts[0]}, {parts[1]}, {parts[2]});", indent
        )
        for part in parts:
            self.emit(f"Py_DecRef({part});", indent)
        return self.checked(target, indent)

    def list_literal(self, node: ast.List, indent: int) -> str:
        """`[a, b, c]` - an empty list, then each element appended.

        PyList_Append does *not* steal its reference, unlike PyTuple_SetItem,
        so each element is released after it goes in.
        """

        target = self.temporary()
        self.emit(f"{target} = PyList_New(0LL);", indent)
        self.checked(target, indent)
        for element in node.elts:
            value = self.expression(element, indent)
            self.emit(f"PyList_Append({target}, {value});", indent)
            self.emit(f"Py_DecRef({value});", indent)
        return target

    def set_literal(self, node: ast.Set, indent: int) -> str:
        """`{a, b}` - built as a list, then handed to the `set` builtin."""

        listed = self.list_literal(
            ast.copy_location(ast.List(elts=node.elts, ctx=ast.Load()), node), indent
        )
        maker = self.builtin("set", indent)
        target = self.temporary()
        self.emit(f"{target} = PyObject_CallOneArg({maker}, {listed});", indent)
        self.emit(f"Py_DecRef({maker});", indent)
        self.emit(f"Py_DecRef({listed});", indent)
        return self.checked(target, indent)

    def comprehension(self, node, indent: int) -> str:
        """`[e for x in it if c]` - the loop it stands for, written out.

        A generator expression is built eagerly into a list here. That is not
        lazy, so an infinite source would not terminate and the memory is spent
        up front; every generator in the programs this targets is consumed
        immediately, which is the case the trade is made for.
        """

        target = self.temporary()
        self.emit(f"{target} = PyList_New(0LL);", indent)
        self.checked(target, indent)
        self.comprehension_clause(node, 0, target, indent)
        if isinstance(node, ast.SetComp):
            maker = self.builtin("set", indent)
            gathered = self.temporary()
            self.emit(
                f"{gathered} = PyObject_CallOneArg({maker}, {target});", indent
            )
            self.emit(f"Py_DecRef({maker});", indent)
            self.emit(f"Py_DecRef({target});", indent)
            return self.checked(gathered, indent)
        return target

    def comprehension_clause(self, node, position: int, target: str, indent: int) -> None:
        """One `for` clause of a comprehension, then whatever follows it."""

        if position == len(node.generators):
            value = self.expression(node.elt, indent)
            self.emit(f"PyList_Append({target}, {value});", indent)
            self.emit(f"Py_DecRef({value});", indent)
            return
        clause = node.generators[position]
        if clause.is_async:
            raise self.fail(node, "an async comprehension is not translated here")
        if not isinstance(clause.target, ast.Name):
            raise self.fail(node, "a comprehension binds one name per clause here")
        sequence = self.expression(clause.iter, indent)
        iterator = self.temporary()
        self.emit(f"{iterator} = PyObject_GetIter({sequence});", indent)
        self.checked(iterator, indent)
        self.emit(f"Py_DecRef({sequence});", indent)
        item = self.temporary()
        bound = self.declare(clause.target.id)
        self.emit("while (1) {", indent)
        self.emit(f"{item} = PyIter_Next({iterator});", indent + 1)
        self.emit(
            f"if (!{item}) {{ if (PyErr_Occurred()) {{ PyErr_Print(); exit(1); }} break; }}",
            indent + 1,
        )
        self.emit(f"if ({bound}) Py_DecRef({bound});", indent + 1)
        self.emit(f"{bound} = {item};", indent + 1)
        inner = indent + 1
        for condition in clause.ifs:
            decision = self.temporary_flag()
            test = self.expression(condition, inner)
            self.emit(f"{decision} = PyObject_IsTrue({test});", inner)
            self.emit(f"Py_DecRef({test});", inner)
            self.emit(f"if ({decision} < 0) {{ PyErr_Print(); exit(1); }}", inner)
            self.emit(f"if ({decision}) {{", inner)
            inner += 1
        self.comprehension_clause(node, position + 1, target, inner)
        for _ in clause.ifs:
            inner -= 1
            self.emit("}", inner)
        self.emit("}", indent)
        self.emit(f"Py_DecRef({iterator});", indent)

    def dict_literal(self, node: ast.Dict, indent: int) -> str:
        """`{k: v}` - an empty dict, then each pair set into it."""

        target = self.temporary()
        self.emit(f"{target} = PyDict_New();", indent)
        self.checked(target, indent)
        for key_node, value_node in zip(node.keys, node.values):
            if key_node is None:
                raise self.fail(node, "`**` in a dict literal is not translated here")
            key = self.expression(key_node, indent)
            value = self.expression(value_node, indent)
            self.emit(f"PyDict_SetItem({target}, {key}, {value});", indent)
            # PyDict_SetItem does not steal either reference, so both go back.
            self.emit(f"Py_DecRef({key});", indent)
            self.emit(f"Py_DecRef({value});", indent)
        return target

    def tuple_literal(self, node: ast.Tuple, indent: int) -> str:
        """`(a, b)` - built through the list the vetted set can grow, then
        handed to the tuple builtin.

        PyTuple_Pack is variadic and py2bin passes no variadic arguments, so
        its vetted arity is fixed at two and cannot serve a general tuple.
        Going through `tuple(list)` costs an allocation and works for any
        length, which is the better trade here.
        """

        listed = self.list_literal(
            ast.copy_location(ast.List(elts=node.elts, ctx=ast.Load()), node), indent
        )
        maker = self.builtin("tuple", indent)
        target = self.temporary()
        self.emit(f"{target} = PyObject_CallOneArg({maker}, {listed});", indent)
        self.emit(f"Py_DecRef({maker});", indent)
        self.emit(f"Py_DecRef({listed});", indent)
        return self.checked(target, indent)

    def builtin(self, name: str, indent: int) -> str:
        """A name from the builtins module, fetched the way Python fetches it.

        `range`, `sum`, `sorted`, `abs`, `dict` - anything the interpreter
        already has. Nothing here reimplements them; the module is imported
        once at startup and this reads an attribute off it.
        """

        target = self.temporary()
        self.emit(
            f"{target} = PyObject_GetAttrString(_py2bin_builtins, "
            f"{_c_string(name)});",
            indent,
        )
        return self.checked(target, indent)

    def attribute(self, node: ast.Attribute, indent: int) -> str:
        value = self.expression(node.value, indent)
        target = self.temporary()
        self.emit(
            f"{target} = PyObject_GetAttrString({value}, {_c_string(node.attr)});",
            indent,
        )
        self.emit(f"Py_DecRef({value});", indent)
        return self.checked(target, indent)

    def identity(self, node: ast.Compare, indent: int) -> str:
        """`a is b` - the same object, which is the same pointer.

        No C-API call is needed or wanted: identity is what the pointers say,
        and asking RichCompare would answer a different question.
        """

        left = self.expression(node.left, indent)
        right = self.expression(node.comparators[0], indent)
        decision = self.temporary_flag()
        operator = "==" if isinstance(node.ops[0], ast.Is) else "!=";
        self.emit(f"{decision} = ({left} {operator} {right});", indent)
        self.emit(f"Py_DecRef({left});", indent)
        self.emit(f"Py_DecRef({right});", indent)
        target = self.temporary()
        self.emit(f"if ({decision}) {{", indent)
        self.emit(
            f'    {target} = PyObject_GetAttrString(_py2bin_builtins, "True");', indent
        )
        self.emit("} else {", indent)
        self.emit(
            f'    {target} = PyObject_GetAttrString(_py2bin_builtins, "False");', indent
        )
        self.emit("}", indent)
        return self.checked(target, indent)

    def membership(self, node: ast.Compare, indent: int) -> str:
        """`x in xs` - PySequence_Contains, which answers 1, 0 or -1.

        The -1 is a failure and not a false, so it is tested for separately;
        treating it as false would turn a raised exception into an answer.
        """

        value = self.expression(node.left, indent)
        container = self.expression(node.comparators[0], indent)
        decision = self.temporary_flag()
        self.emit(f"{decision} = PySequence_Contains({container}, {value});", indent)
        self.emit(f"Py_DecRef({value});", indent)
        self.emit(f"Py_DecRef({container});", indent)
        self.emit(f"if ({decision} < 0) {{ PyErr_Print(); exit(1); }}", indent)
        if isinstance(node.ops[0], ast.NotIn):
            self.emit(f"{decision} = !{decision};", indent)
        target = self.temporary()
        self.emit(f"if ({decision}) {{", indent)
        self.emit(
            f'    {target} = PyObject_GetAttrString(_py2bin_builtins, "True");', indent
        )
        self.emit("} else {", indent)
        self.emit(
            f'    {target} = PyObject_GetAttrString(_py2bin_builtins, "False");', indent
        )
        self.emit("}", indent)
        return self.checked(target, indent)

    def call(self, node: ast.Call, indent: int) -> str:
        if isinstance(node.func, ast.Attribute):
            return self.method_call(node, indent)
        if not isinstance(node.func, ast.Name):
            raise self.fail(node, "only a call to a named function is translated here")
        if node.func.id == "len":
            if len(node.args) != 1:
                raise self.fail(node, "len() takes one argument")
            value = self.expression(node.args[0], indent)
            target = self.temporary()
            self.emit(f"{target} = PyLong_FromLongLong(PyObject_Size({value}));", indent)
            self.emit(f"Py_DecRef({value});", indent)
            return self.checked(target, indent)
        if node.func.id == "str":
            if len(node.args) != 1:
                raise self.fail(node, "str() takes one argument")
            value = self.expression(node.args[0], indent)
            target = self.temporary()
            self.emit(f"{target} = PyObject_Str({value});", indent)
            self.emit(f"Py_DecRef({value});", indent)
            return self.checked(target, indent)
        if node.func.id not in self.known_functions:
            assert self.current is not None
            if self.reference(node.func.id) is not None:
                # A name the program bound - an imported one, or a value
                # holding something callable. It wins over the builtin of the
                # same spelling, exactly as it does in Python.
                callable_value = self.name(
                    ast.copy_location(
                        ast.Name(id=node.func.id, ctx=ast.Load()), node
                    ),
                    indent,
                )
            else:
                # Not one of ours, so ask the interpreter for it.
                callable_value = self.builtin(node.func.id, indent)
            target = self.invoke(callable_value, node.args, indent, node.keywords)
            self.emit(f"Py_DecRef({callable_value});", indent)
            return target
        expected, defaulted = self.known_functions[node.func.id]
        if not expected - defaulted <= len(node.args) <= expected:
            raise self.fail(
                node,
                f"{node.func.id}() takes {expected - defaulted} to {expected} "
                f"argument(s), {len(node.args)} given",
            )
        arguments = [self.expression(item, indent) for item in node.args]
        # A parameter the call leaves out is passed as NULL and the callee puts
        # its default in - evaluated there rather than here, so the default
        # expression exists once however many call sites there are.
        arguments.extend(["(PyObject *)0"] * (expected - len(node.args)))
        target = self.temporary()
        self.emit(f"{target} = f_{node.func.id}({', '.join(arguments)});", indent)
        for argument in arguments:
            # An omitted parameter went in as NULL, which is not a reference
            # and must not be released.
            if argument != "(PyObject *)0":
                self.emit(f"Py_DecRef({argument});", indent)
        return self.checked(target, indent)

    def invoke_with_keywords(
        self, callable_value: str, args: list, keywords: list, indent: int
    ) -> str:
        """`f(a, key=b)` - a tuple for the positional part, a dict for the rest."""

        values = [self.expression(item, indent) for item in args]
        holder = self.temporary()
        self.emit(f"{holder} = PyTuple_New({len(values)}LL);", indent)
        self.checked(holder, indent)
        for position, value in enumerate(values):
            # Steals the reference, so the value is not released after this.
            self.emit(f"PyTuple_SetItem({holder}, {position}LL, {value});", indent)
        mapping = self.temporary()
        self.emit(f"{mapping} = PyDict_New();", indent)
        self.checked(mapping, indent)
        for keyword in keywords:
            if keyword.arg is None:
                raise self.fail(
                    keyword.value, "`**kwargs` at a call is not translated here yet"
                )
            key = self.temporary()
            self.emit(f"{key} = PyUnicode_FromString({_c_string(keyword.arg)});", indent)
            self.checked(key, indent)
            value = self.expression(keyword.value, indent)
            self.emit(f"PyDict_SetItem({mapping}, {key}, {value});", indent)
            # Does not steal either reference, so both go back.
            self.emit(f"Py_DecRef({key});", indent)
            self.emit(f"Py_DecRef({value});", indent)
        target = self.temporary()
        self.emit(
            f"{target} = PyObject_Call({callable_value}, {holder}, {mapping});", indent
        )
        self.emit(f"Py_DecRef({holder});", indent)
        self.emit(f"Py_DecRef({mapping});", indent)
        return self.checked(target, indent)

    def method_call(self, node: ast.Call, indent: int) -> str:
        """`x.f()` and `x.f(a)` - the two arities the vetted set can call.

        More arguments need PyObject_Call and a tuple to put them in, and
        neither is in the vetted set, so they are refused by name rather than
        approximated.
        """

        assert isinstance(node.func, ast.Attribute)
        callable_value = self.attribute(node.func, indent)
        target = self.invoke(callable_value, node.args, indent, node.keywords)
        self.emit(f"Py_DecRef({callable_value});", indent)
        return self.checked(target, indent)

    def invoke(
        self, callable_value: str, args: list, indent: int, keywords: list = ()
    ) -> str:
        """Call something with any number of arguments.

        Nought and one positional arguments have their own entry points; beyond
        that, and whenever there are keywords, the arguments go into a tuple and
        the keywords into a dict for PyObject_Call. PyTuple_SetItem *steals* the
        reference it is given, which is why nothing is released after it -
        releasing again would be a second drop of a reference this code no
        longer owns. PyDict_SetItem does not steal, so those are released.
        """

        if keywords:
            return self.invoke_with_keywords(callable_value, args, keywords, indent)
        target = self.temporary()
        if not args:
            self.emit(f"{target} = PyObject_CallNoArgs({callable_value});", indent)
            return self.checked(target, indent)
        if len(args) == 1:
            argument = self.expression(args[0], indent)
            self.emit(
                f"{target} = PyObject_CallOneArg({callable_value}, {argument});", indent
            )
            self.emit(f"Py_DecRef({argument});", indent)
            return self.checked(target, indent)
        values = [self.expression(item, indent) for item in args]
        holder = self.temporary()
        self.emit(f"{holder} = PyTuple_New({len(values)}LL);", indent)
        for position, value in enumerate(values):
            self.emit(f"PyTuple_SetItem({holder}, {position}LL, {value});", indent)
        self.emit(f"{target} = PyObject_Call({callable_value}, {holder}, 0);", indent)
        self.emit(f"Py_DecRef({holder});", indent)
        return self.checked(target, indent)

    # --- statements ------------------------------------------------------

    def statement(self, node: ast.stmt, indent: int) -> None:
        if isinstance(node, ast.Assign):
            self.assignment(node, indent)
        elif isinstance(node, ast.Expr):
            self.expression_statement(node, indent)
        elif isinstance(node, ast.If):
            self.conditional(node, indent)
        elif isinstance(node, ast.While):
            self.loop(node, indent)
        elif isinstance(node, ast.For):
            self.for_loop(node, indent)
        elif isinstance(node, ast.Return):
            self.give_back(node, indent)
        elif isinstance(node, ast.Import):
            self.import_module(node, indent)
        elif isinstance(node, ast.ImportFrom):
            self.import_names(node, indent)
        elif isinstance(node, ast.Delete):
            self.remove(node, indent)
        elif isinstance(node, ast.Raise):
            self.throw(node, indent)
        elif isinstance(node, ast.With):
            self.with_block(node, indent)
        elif isinstance(node, ast.Global):
            # Every name lives in one C scope per function here, and the module
            # body is its own function, so a `global` declaration names storage
            # that is already shared. Nothing to emit.
            pass
        elif isinstance(node, ast.Try):
            self.guarded(node, indent)
        elif isinstance(node, ast.AugAssign):
            self.augmented(node, indent)
        elif isinstance(node, ast.Break):
            self.emit("break;", indent)
        elif isinstance(node, ast.Continue):
            self.emit("continue;", indent)
        elif isinstance(node, ast.Pass):
            pass
        elif isinstance(node, ast.FunctionDef):
            raise self.fail(node, "a nested function is not translated here yet")
        else:
            raise self.fail(
                node, f"{type(node).__name__} has no C-API translation here yet"
            )

    def import_module(self, node: ast.Import, indent: int) -> None:
        """`import x` - the module object, bound to a name like any value.

        This is where the tier earns its cost. The interpreter is present and
        its import machinery works, so a compiled program can reach anything
        installed beside it - which is the whole reason to pay for libpython.
        """

        for alias in node.names:
            if "." in alias.name:
                raise self.fail(node, "a dotted import is not translated here yet")
            target = self.declare(alias.asname or alias.name)
            self.emit(f"if ({target}) Py_DecRef({target});", indent)
            self.emit(
                f'{target} = PyImport_ImportModule({_c_string(alias.name)});', indent
            )
            self.checked(target, indent)

    def import_names(self, node: ast.ImportFrom, indent: int) -> None:
        """`from x import a, b` - import the module, then read the names off it.

        A dotted module works because the import machinery is the
        interpreter's: `from scipy import optimize` imports `scipy` and takes
        the attribute, exactly as the statement means.
        """

        if node.level:
            raise self.fail(node, "a relative import is not translated here yet")
        if node.module is None:
            raise self.fail(node, "this import form is not translated here yet")
        module = self.temporary()
        self.emit(
            f"{module} = PyImport_ImportModule({_c_string(node.module)});", indent
        )
        self.checked(module, indent)
        for alias in node.names:
            if alias.name == "*":
                raise self.fail(node, "`import *` is not translated here yet")
            target = self.declare(alias.asname or alias.name)
            self.emit(f"if ({target}) Py_DecRef({target});", indent)
            self.emit(
                f"{target} = PyObject_GetAttrString({module}, "
                f"{_c_string(alias.name)});",
                indent,
            )
            # A name that is not an attribute may be a submodule that has not
            # been imported yet - `from matplotlib import pyplot` is exactly
            # that. Python's import system tries the submodule at this point,
            # so this does too, and the failed lookup is cleared first because
            # an exception left set would surface at the next call.
            dotted = f"{node.module}.{alias.name}"
            self.emit(f"if (!{target}) {{", indent)
            self.emit("    PyErr_Clear();", indent)
            self.emit(
                f"    {target} = PyImport_ImportModule({_c_string(dotted)});", indent
            )
            self.emit("}", indent)
            self.checked(target, indent)
        self.emit(f"Py_DecRef({module});", indent)

    def assignment(self, node: ast.Assign, indent: int) -> None:
        if len(node.targets) != 1:
            raise self.fail(node, "only one assignment target is translated here")
        if isinstance(node.targets[0], ast.Subscript):
            self.store_item(node.targets[0], node.value, indent)
            return
        if isinstance(node.targets[0], (ast.Tuple, ast.List)):
            self.unpack(node.targets[0], node.value, indent)
            return
        if not isinstance(node.targets[0], ast.Name):
            raise self.fail(node, "only a name or a subscript is assigned to here")
        value = self.expression(node.value, indent)
        target = self.declare(node.targets[0].id)
        # The name may already hold something; that reference is released
        # before it is overwritten, which is what keeps a loop from growing.
        self.emit(f"if ({target}) Py_DecRef({target});", indent)
        self.emit(f"{target} = {value};", indent)

    def remove(self, node: ast.Delete, indent: int) -> None:
        """`del xs[k]` - the only del shape with an object-protocol answer.

        `del name` unbinds, and a C local has nothing that records being
        unbound, so it is refused rather than turned into a store of None.
        """

        for target in node.targets:
            if not isinstance(target, ast.Subscript):
                raise self.fail(
                    target,
                    "only `del container[key]` is translated here; deleting a "
                    "name has nothing to record being unbound",
                )
            container = self.expression(target.value, indent)
            key = (
                self.slice_object(target.slice, indent)
                if isinstance(target.slice, ast.Slice)
                else self.expression(target.slice, indent)
            )
            outcome = self.temporary_flag()
            self.emit(f"{outcome} = PyObject_DelItem({container}, {key});", indent)
            self.emit(f"Py_DecRef({container});", indent)
            self.emit(f"Py_DecRef({key});", indent)
            self.emit(f"if ({outcome} < 0) {{ PyErr_Print(); exit(1); }}", indent)

    def throw(self, node: ast.Raise, indent: int) -> None:
        """`raise E(...)` - set the exception, then take the failure path.

        Setting it is all the C API does; unwinding is the caller's business,
        and here that is the same `goto` a failing call takes.
        """

        if node.cause is not None:
            raise self.fail(node, "`raise ... from ...` is not translated here yet")
        if node.exc is None:
            raise self.fail(node, "a bare re-raise is not translated here yet")
        value = self.expression(node.exc, indent)
        # PyErr_SetObject wants the class as well as the value, and a NULL
        # there sets nothing at all - the raise then vanished without a trace.
        # `type(value)` is the class whether the source named a class or built
        # an instance, so it answers both shapes.
        kind = self.builtin("type", indent)
        classified = self.temporary()
        self.emit(f"{classified} = PyObject_CallOneArg({kind}, {value});", indent)
        self.emit(f"Py_DecRef({kind});", indent)
        self.checked(classified, indent)
        self.emit(f"PyErr_SetObject({classified}, {value});", indent)
        self.emit(f"Py_DecRef({classified});", indent)
        self.emit(f"Py_DecRef({value});", indent)
        if self.handlers:
            self.emit(f"goto {self.handlers[-1]};", indent)
        else:
            self.emit("PyErr_Print(); exit(1);", indent)

    def with_block(self, node: ast.With, indent: int) -> None:
        """`with a as b:` - __enter__, the body, then __exit__.

        __exit__ is called on the way out of the body. It is *not* called when
        the body raises, because that needs the exception threaded into the
        three arguments it takes, and pretending otherwise would silently skip
        a close. A body that raises inside a `with` is refused rather than
        mishandled.
        """

        if len(node.items) > 1:
            inner = ast.copy_location(
                ast.With(items=node.items[1:], body=node.body, type_comment=None),
                node,
            )
            ast.fix_missing_locations(inner)
            node = ast.copy_location(
                ast.With(items=node.items[:1], body=[inner], type_comment=None),
                node,
            )
        item = node.items[0]
        manager = self.expression(item.context_expr, indent)
        entered = self.temporary()
        enter = self.temporary()
        self.emit(
            f'{enter} = PyObject_GetAttrString({manager}, "__enter__");', indent
        )
        self.checked(enter, indent)
        self.emit(f"{entered} = PyObject_CallNoArgs({enter});", indent)
        self.emit(f"Py_DecRef({enter});", indent)
        self.checked(entered, indent)
        if item.optional_vars is not None:
            if not isinstance(item.optional_vars, ast.Name):
                raise self.fail(node, "`with ... as` binds one name here")
            target = self.declare(item.optional_vars.id)
            self.emit(f"if ({target}) Py_DecRef({target});", indent)
            self.emit(f"Py_IncRef({entered});", indent)
            self.emit(f"{target} = {entered};", indent)
        for statement in node.body:
            self.statement(statement, indent)
        exit_call = self.temporary()
        self.emit(
            f'{exit_call} = PyObject_GetAttrString({manager}, "__exit__");', indent
        )
        self.checked(exit_call, indent)
        none = self.builtin("None", indent)
        arguments = self.temporary()
        self.emit(f"{arguments} = PyTuple_New(3LL);", indent)
        self.checked(arguments, indent)
        for position in range(3):
            self.emit(f"Py_IncRef({none});", indent)
            self.emit(f"PyTuple_SetItem({arguments}, {position}LL, {none});", indent)
        outcome = self.temporary()
        self.emit(
            f"{outcome} = PyObject_Call({exit_call}, {arguments}, (PyObject *)0);",
            indent,
        )
        self.emit(f"Py_DecRef({exit_call});", indent)
        self.emit(f"Py_DecRef({arguments});", indent)
        self.emit(f"Py_DecRef({none});", indent)
        self.checked(outcome, indent)
        self.emit(f"Py_DecRef({outcome});", indent)
        self.emit(f"Py_DecRef({entered});", indent)
        self.emit(f"Py_DecRef({manager});", indent)

    def guarded(self, node: ast.Try, indent: int) -> None:
        """`try: ... except E: ...` - the body, then a handler it jumps to.

        A C-API call that fails leaves an exception set and answers NULL, and
        inside a `try` that NULL becomes a jump rather than the end of the
        process. `PyErr_ExceptionMatches` asks whether the exception is the
        class this clause catches, exactly as the interpreter asks it.
        """

        if node.finalbody:
            raise self.fail(node, "a finally clause is not translated here yet")
        if node.orelse:
            raise self.fail(node, "a try-else is not translated here yet")
        assert self.current is not None
        self.current.temporaries += 1
        number = self.current.temporaries
        handler = f"_handler{number}"
        done = f"_after{number}"
        # The classes each clause catches are evaluated here, before the body
        # runs. Building them inside the handler calls into Python while an
        # exception is set, which CPython refuses - `except (A, B)` failed with
        # "returned a result with an exception set" until this moved out.
        caught: list[str | None] = []
        for clause in node.handlers:
            caught.append(
                None if clause.type is None else self.expression(clause.type, indent)
            )
        self.handlers.append(handler)
        try:
            for statement in node.body:
                self.statement(statement, indent)
        finally:
            self.handlers.pop()
        self.emit(f"goto {done};", indent)
        self.emit(f"{handler}:", 0)
        for clause, wanted in zip(node.handlers, caught):
            if clause.type is None:
                # A bare except catches whatever is set.
                self.bind_exception(clause, indent)
                for statement in clause.body:
                    self.statement(statement, indent)
                self.emit(f"goto {done};", indent)
                continue
            # PyErr_ExceptionMatches takes a tuple as readily as a class.
            decision = self.temporary_flag()
            self.emit(f"{decision} = PyErr_ExceptionMatches({wanted});", indent)
            self.emit(f"Py_DecRef({wanted});", indent)
            self.emit(f"if ({decision}) {{", indent)
            self.bind_exception(clause, indent + 1)
            for statement in clause.body:
                self.statement(statement, indent + 1)
            self.emit(f"    goto {done};", indent)
            self.emit("}", indent)
        # Nothing matched, so the exception carries on outward.
        if self.handlers:
            self.emit(f"goto {self.handlers[-1]};", indent)
        else:
            self.emit("PyErr_Print(); exit(1);", indent)
        self.emit(f"{done}:", 0)
        self.emit(";", indent)

    def bind_exception(self, clause: ast.ExceptHandler, indent: int) -> None:
        """Clear the exception, binding it first when the clause names it.

        Taking it is what clears it, so `except E as name` and a bare `except`
        differ only in whether the object is kept.
        """

        if clause.name is None:
            self.emit("PyErr_Clear();", indent)
            return
        caught = self.temporary()
        self.emit(f"{caught} = PyErr_GetRaisedException();", indent)
        target = self.declare(clause.name)
        self.emit(f"if ({target}) Py_DecRef({target});", indent)
        self.emit(f"{target} = {caught};", indent)

    def augmented(self, node: ast.AugAssign, indent: int) -> None:
        """`x += 1` - the operation, then the assignment, as Python does it."""

        if not isinstance(node.target, ast.Name):
            raise self.fail(node, "only augmented assignment to a name is translated")
        rewritten = ast.copy_location(
            ast.BinOp(
                left=ast.copy_location(
                    ast.Name(id=node.target.id, ctx=ast.Load()), node
                ),
                op=node.op,
                right=node.value,
            ),
            node,
        )
        value = self.expression(rewritten, indent)
        target = self.declare(node.target.id)
        self.emit(f"if ({target}) Py_DecRef({target});", indent)
        self.emit(f"{target} = {value};", indent)

    def unpack(self, target, value_node: ast.expr, indent: int) -> None:
        """`a, b = pair` - the value once, then each name from its position.

        Indexed rather than iterated, which is not what Python does for an
        arbitrary iterable but is right for the sequences this is written for
        and does not need the iterator threaded through the assignment.
        """

        for element in target.elts:
            if not isinstance(element, ast.Name):
                raise self.fail(target, "unpacking binds plain names here")
        value = self.expression(value_node, indent)
        self.unpack_value(target, value, indent)
        self.emit(f"Py_DecRef({value});", indent)

    def unpack_value(self, target, value: str, indent: int) -> None:
        """Take ``value`` apart into the names of ``target``."""

        for element in target.elts:
            if not isinstance(element, ast.Name):
                raise self.fail(target, "unpacking binds plain names here")
        for position, element in enumerate(target.elts):
            index = self.temporary()
            self.emit(f"{index} = PyLong_FromLongLong({position}LL);", indent)
            self.checked(index, indent)
            item = self.temporary()
            self.emit(f"{item} = PyObject_GetItem({value}, {index});", indent)
            self.emit(f"Py_DecRef({index});", indent)
            self.checked(item, indent)
            name = self.declare(element.id)
            self.emit(f"if ({name}) Py_DecRef({name});", indent)
            self.emit(f"{name} = {item};", indent)

    def store_item(
        self, target: ast.Subscript, value_node: ast.expr, indent: int
    ) -> None:
        """`xs[k] = v` - the object protocol, so a list and a dict both work."""

        if isinstance(target.slice, ast.Slice):
            raise self.fail(target, "assigning to a slice is not translated here yet")
        container = self.expression(target.value, indent)
        key = self.expression(target.slice, indent)
        value = self.expression(value_node, indent)
        outcome = self.temporary_flag()
        self.emit(
            f"{outcome} = PyObject_SetItem({container}, {key}, {value});", indent
        )
        for held in (container, key, value):
            self.emit(f"Py_DecRef({held});", indent)
        self.emit(f"if ({outcome} < 0) {{ PyErr_Print(); exit(1); }}", indent)

    def expression_statement(self, node: ast.Expr, indent: int) -> None:
        if (
            isinstance(node.value, ast.Call)
            and isinstance(node.value.func, ast.Name)
            and node.value.func.id == "print"
        ):
            self.write_out(node.value, indent)
            return
        value = self.expression(node.value, indent)
        self.emit(f"Py_DecRef({value});", indent)

    def write_out(self, node: ast.Call, indent: int) -> None:
        """print(...) - straight to sys.stdout through the file API."""

        if node.keywords:
            raise self.fail(node, "print() keyword arguments are not translated here")
        stream = self.temporary()
        self.emit(f'{stream} = PySys_GetObject("stdout");', indent)
        for position, argument in enumerate(node.args):
            if position:
                self.emit(f'PyFile_WriteString(" ", {stream});', indent)
            value = self.expression(argument, indent)
            # Py_PRINT_RAW is 1: str() of the object rather than its repr,
            # which is what print writes.
            self.emit(f"PyFile_WriteObject({value}, {stream}, 1);", indent)
            self.emit(f"Py_DecRef({value});", indent)
        self.emit(f'PyFile_WriteString("\\n", {stream});', indent)

    def conditional(self, node: ast.If, indent: int) -> None:
        test = self.expression(node.test, indent)
        decision = self.temporary_flag()
        self.emit(f"{decision} = PyObject_IsTrue({test});", indent)
        self.emit(f"Py_DecRef({test});", indent)
        self.emit(f"if ({decision}) {{", indent)
        for statement in node.body:
            self.statement(statement, indent + 1)
        if node.orelse:
            self.emit("} else {", indent)
            for statement in node.orelse:
                self.statement(statement, indent + 1)
        self.emit("}", indent)

    def loop(self, node: ast.While, indent: int) -> None:
        if node.orelse:
            raise self.fail(node, "a while-else is not translated here yet")
        decision = self.temporary_flag()
        self.emit("while (1) {", indent)
        test = self.expression(node.test, indent + 1)
        self.emit(f"{decision} = PyObject_IsTrue({test});", indent + 1)
        self.emit(f"Py_DecRef({test});", indent + 1)
        self.emit(f"if (!{decision}) break;", indent + 1)
        for statement in node.body:
            self.statement(statement, indent + 1)
        self.emit("}", indent)

    def for_loop(self, node: ast.For, indent: int) -> None:
        """`for x in seq:` - the iterator protocol, exactly as Python runs it.

        `range(...)`, a list, a string, a file, a generator: whatever the
        object offers, because the interpreter is the one being asked. That is
        the difference from the native tier, which has to know the shape of
        every iterable it supports.
        """

        if node.orelse:
            raise self.fail(node, "a for-else is not translated here yet")
        if not isinstance(node.target, (ast.Name, ast.Tuple, ast.List)):
            raise self.fail(node, "a for loop binds a name or a tuple of names")
        sequence = self.expression(node.iter, indent)
        iterator = self.temporary()
        self.emit(f"{iterator} = PyObject_GetIter({sequence});", indent)
        self.checked(iterator, indent)
        self.emit(f"Py_DecRef({sequence});", indent)
        item = self.temporary()
        target = (
            self.declare(node.target.id)
            if isinstance(node.target, ast.Name)
            else None
        )
        self.emit("while (1) {", indent)
        self.emit(f"{item} = PyIter_Next({iterator});", indent + 1)
        # NULL means the sequence ended, or that producing the next item
        # failed. Asking whether an exception is set is what tells them apart.
        self.emit(
            f"if (!{item}) {{ if (PyErr_Occurred()) {{ PyErr_Print(); exit(1); }} break; }}",
            indent + 1,
        )
        if target is None:
            # `for a, b in pairs` - the item is taken apart the way an
            # assignment to the same target would take it apart.
            self.unpack_value(node.target, item, indent + 1)
            self.emit(f"Py_DecRef({item});", indent + 1)
        else:
            self.emit(f"if ({target}) Py_DecRef({target});", indent + 1)
            self.emit(f"{target} = {item};", indent + 1)
        for statement in node.body:
            self.statement(statement, indent + 1)
        self.emit("}", indent)
        self.emit(f"Py_DecRef({iterator});", indent)

    def temporary_flag(self) -> str:
        assert self.current is not None
        self.current.temporaries += 1
        name = f"_c{self.current.temporaries}"
        if name not in self.current.locals:
            self.current.locals.append("int " + name)
        return name

    def give_back(self, node: ast.Return, indent: int) -> None:
        # A bare return is `return None`, which is what falling off the end
        # gives too.
        value = (
            self.builtin("None", indent)
            if node.value is None
            else self.expression(node.value, indent)
        )
        self.release_locals(indent)
        self.emit(f"return {value};", indent)

    def release_locals(self, indent: int) -> None:
        """Give back what the body still holds, on the way out.

        Every name the body bound owns a reference, and leaving without
        releasing them leaks one per call - which a recursive function turns
        into one per level. The value being returned is a temporary and is not
        in this list, so it survives.
        """

        assert self.current is not None
        for name in self.current.parameters:
            self.emit(f"Py_DecRef(p_{name});", indent)
        for name in self.current.locals:
            # Only the names the program bound. A temporary was released where
            # it was consumed, so releasing it again here would be a second
            # drop of a reference this code no longer owns.
            if not name.startswith("v_"):
                continue
            self.emit(f"if ({name}) Py_DecRef({name});", indent)

    # --- assembly --------------------------------------------------------

    def module(self, tree: ast.Module) -> str:
        for node in tree.body:
            if isinstance(node, ast.FunctionDef):
                arguments = node.args
                if (
                    node.decorator_list
                    or arguments.vararg
                    or arguments.kwarg
                    or arguments.kwonlyargs
                ):
                    raise self.fail(
                        node,
                        "a decorated function, or one taking *args, **kwargs "
                        "or keyword-only parameters, is not translated here yet",
                    )
                self.known_functions[node.name] = (
                    len(arguments.args),
                    len(arguments.defaults),
                )

        # What the module body binds, gathered before any function is written:
        # a function may read a global defined further down the file, exactly
        # as it may in Python, so the set has to be complete first.
        for node in tree.body:
            self.note_module_bindings(node)

        for node in tree.body:
            if isinstance(node, ast.FunctionDef):
                self.write_function(node)

        entry = _Function("main", ())
        self.current = entry
        self.at_module_level = True
        for node in tree.body:
            if isinstance(node, ast.FunctionDef):
                continue
            self.statement(node, 2)
        self.at_module_level = False
        self.functions.append(entry)
        self.current = None
        return self.render()

    def note_module_bindings(self, node: ast.stmt) -> None:
        """Record every name this module-level statement binds."""

        if isinstance(node, ast.Assign):
            for target in node.targets:
                for element in (
                    target.elts
                    if isinstance(target, (ast.Tuple, ast.List))
                    else [target]
                ):
                    if isinstance(element, ast.Name):
                        self.globals.add(element.id)
        elif isinstance(node, (ast.AugAssign, ast.For)) and isinstance(
            node.target, ast.Name
        ):
            self.globals.add(node.target.id)
        elif isinstance(node, (ast.Import, ast.ImportFrom)):
            for alias in node.names:
                if alias.name != "*":
                    self.globals.add(alias.asname or alias.name.split(".")[0])
        elif isinstance(node, ast.With):
            for item in node.items:
                if isinstance(item.optional_vars, ast.Name):
                    self.globals.add(item.optional_vars.id)
        # A name bound inside a module-level if/for/while/try is still global.
        for field in ("body", "orelse", "finalbody"):
            for inner in getattr(node, field, []) or []:
                self.note_module_bindings(inner)
        for handler in getattr(node, "handlers", []) or []:
            for inner in handler.body:
                self.note_module_bindings(inner)

    def write_function(self, node: ast.FunctionDef) -> None:
        parameters = tuple(argument.arg for argument in node.args.args)
        defaults = node.args.defaults
        function = _Function(node.name, parameters, len(defaults))
        self.current = function
        # A parameter the call left out arrives as NULL and takes its default
        # here, before the increments below, so there is one rule for what the
        # body owns.
        for offset, default in enumerate(defaults):
            name = parameters[len(parameters) - len(defaults) + offset]
            self.emit(f"if (!p_{name}) {{", 1)
            value = self.expression(default, 2)
            self.emit(f"    Py_IncRef({value});", 1)
            self.emit(f"    p_{name} = {value};", 1)
            self.emit(f"    Py_DecRef({value});", 1)
            self.emit("}", 1)
        # The body owns its parameters, so rebinding one releases what it held
        # rather than dropping a reference the caller still owns.
        for name in parameters:
            self.emit(f"Py_IncRef(p_{name});", 1)
        for statement in node.body:
            self.statement(statement, 1)
        # Falling off the end is `return None` in Python.
        tail = self.builtin("None", 1)
        self.release_locals(1)
        self.emit(f"return {tail};", 1)
        self.functions.append(function)
        self.current = None

    def render(self) -> str:
        out = [_PROTOTYPES]
        for function in self.functions:
            if function.name == "main":
                continue
            arguments = ", ".join(
                f"PyObject *p_{name}" for name in function.parameters
            ) or "void"
            out.append(f"static PyObject *f_{function.name}({arguments});")
        out.append("")
        for function in self.functions:
            if function.name == "main":
                continue
            arguments = ", ".join(
                f"PyObject *p_{name}" for name in function.parameters
            ) or "void"
            out.append(f"static PyObject *f_{function.name}({arguments}) {{")
            out.extend(self.declarations(function, 1))
            out.extend(function.body)
            out.append("}")
            out.append("")
        entry = self.functions[-1]
        out.append("static PyObject *_py2bin_builtins = 0;")
        for name in sorted(self.globals):
            out.append(f"static PyObject *g_{name} = 0;")
        out.append("")
        out.append("int main(void) {")
        out.append("    Py_Initialize();")
        out.append('    _py2bin_builtins = PyImport_ImportModule("builtins");')
        out.append(
            "    if (!_py2bin_builtins) { PyErr_Print(); exit(1); }"
        )
        # An embedded interpreter picks its own stdout encoding, and it is not
        # always UTF-8; a program that prints text outside ASCII would stop
        # with a UnicodeEncodeError that has nothing to do with the program.
        setup = "import sys; sys.stdout.reconfigure(encoding='utf-8')"
        out.append(f"    PyRun_SimpleString({_c_string(setup)});")
        out.append("    {")
        out.extend(self.declarations(entry, 2))
        out.extend(entry.body)
        out.append("    }")
        out.append("    Py_Finalize();")
        out.append("    return 0;")
        out.append("}")
        return "\n".join(out) + "\n"

    @staticmethod
    def declarations(function: _Function, depth: int) -> list[str]:
        lines = []
        pad = "    " * depth
        for name in function.locals:
            if name.startswith("int "):
                lines.append(f"{pad}{name} = 0;")
            else:
                lines.append(f"{pad}PyObject *{name} = 0;")
        return lines


def python_to_capi_c(source: str, path: Path | str = "<string>") -> str:
    """Translate a Python module into C that drives the CPython C API."""

    return CApiEmitter(Path(path)).module(ast.parse(source))
