"""Pure-Python Python -> C source and portable C-container backend."""

from __future__ import annotations

import ast
import binascii
import dataclasses
import struct
from pathlib import Path


MAGIC = b"PY2CBIN\0"
VERSION = 1
HEADER = struct.Struct("<8sHHII")


class CSourceError(SyntaxError):
    def __init__(self, message: str, node: ast.AST | None = None):
        if node is not None and getattr(node, "lineno", None):
            message = f"line {node.lineno}:{getattr(node, 'col_offset', 0) + 1}: {message}"
        super().__init__(message)


@dataclasses.dataclass(frozen=True, slots=True)
class CPlan:
    backend: str
    imports: tuple[str, ...]
    reason: str


@dataclasses.dataclass(frozen=True, slots=True)
class CArtifact:
    artifact: Path
    kind: str
    bytes: int


def _imports(tree: ast.AST) -> tuple[str, ...]:
    result: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            result.update(alias.name.split(".", 1)[0] for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module:
            result.add(node.module.split(".", 1)[0])
    return tuple(sorted(result))


def plan_c(source: str, filename: str = "<string>") -> CPlan:
    tree = ast.parse(source, filename=filename)
    imports = _imports(tree)
    if imports:
        return CPlan("cpython-bundle", imports, "imports need compatible target library binaries")
    try:
        _CWriter().compile(tree)
    except CSourceError as error:
        return CPlan("cpython-bundle", (), str(error))
    return CPlan("c-source", (), "program is supported by the C subset")


def compile_to_c(source: str, filename: str = "<string>") -> str:
    tree = ast.parse(source, filename=filename)
    imports = _imports(tree)
    if imports:
        raise CSourceError(
            "imports require a compatible CPython bundle, not standalone C: "
            + ", ".join(imports)
        )
    return _CWriter().compile(tree)


def encode_c_container(c_source: str) -> bytes:
    payload = c_source.encode("utf-8")
    checksum = binascii.crc32(payload) & 0xFFFFFFFF
    return HEADER.pack(MAGIC, VERSION, 0, len(payload), checksum) + payload


def decode_c_container(data: bytes) -> str:
    if len(data) < HEADER.size:
        raise ValueError("truncated C container")
    magic, version, _flags, size, checksum = HEADER.unpack_from(data)
    if magic != MAGIC:
        raise ValueError("invalid C container magic")
    if version != VERSION:
        raise ValueError(f"unsupported C container version {version}")
    payload = data[HEADER.size:]
    if len(payload) != size:
        raise ValueError("invalid C container payload length")
    if binascii.crc32(payload) & 0xFFFFFFFF != checksum:
        raise ValueError("C container checksum mismatch")
    return payload.decode("utf-8")


def compile_c_file(entry: Path, output: Path, *, container: bool = False, clean: bool = False) -> CArtifact:
    entry = entry.expanduser().resolve()
    output = output.expanduser().resolve()
    if not entry.is_file():
        raise FileNotFoundError(f"entry script does not exist: {entry}")
    if output.exists() and not clean:
        raise FileExistsError(f"output already exists: {output} (use --clean)")
    c_source = compile_to_c(entry.read_text(encoding="utf-8"), str(entry))
    data = encode_c_container(c_source) if container else c_source.encode("utf-8")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_bytes(data)
    return CArtifact(output, "py2cbin" if container else "c", len(data))


class _CWriter:
    BIN = {
        ast.Add: "+", ast.Sub: "-", ast.Mult: "*", ast.Mod: "%",
        ast.LShift: "<<", ast.RShift: ">>", ast.BitOr: "|",
        ast.BitXor: "^", ast.BitAnd: "&",
    }
    CMP = {ast.Eq: "==", ast.NotEq: "!=", ast.Lt: "<", ast.LtE: "<=", ast.Gt: ">", ast.GtE: ">="}
    AUG = {
        ast.Add: "+=", ast.Sub: "-=", ast.Mult: "*=", ast.Div: "/=",
        ast.FloorDiv: "/=", ast.Mod: "%=", ast.LShift: "<<=",
        ast.RShift: ">>=", ast.BitOr: "|=", ast.BitXor: "^=", ast.BitAnd: "&=",
    }

    def __init__(self):
        self.lines: list[str] = []
        self.depth = 0
        self.scope: dict[str, str] = {}
        self.returns: dict[str, str] = {}

    def compile(self, tree: ast.Module) -> str:
        functions = [node for node in tree.body if isinstance(node, ast.FunctionDef)]
        body = [node for node in tree.body if not isinstance(node, ast.FunctionDef)]
        for function in functions:
            self.returns[function.name] = self.annotation(function.returns, "long long")
        self.lines += [
            "/* Generated by py2bin: Python -> C. */", "#include <stdio.h>",
            "#include <math.h>", "#include <string.h>", "",
        ]
        for function in functions:
            self.function(function)
            self.lines.append("")
        self.line("int main(void) {")
        self.depth += 1
        self.scope = {}
        self.predeclare(body)
        for statement in body:
            self.statement(statement)
        self.line("return 0;")
        self.depth -= 1
        self.line("}")
        return "\n".join(self.lines) + "\n"

    def line(self, text: str) -> None:
        self.lines.append("    " * self.depth + text)

    def annotation(self, node: ast.expr | None, default: str | None = None) -> str:
        if node is None:
            if default is not None:
                return default
            raise CSourceError("a type annotation is required")
        if isinstance(node, ast.Constant) and node.value is None:
            return "void"
        if isinstance(node, ast.Name) and node.id in {"int", "bool", "float", "str", "None"}:
            return {"int": "long long", "bool": "long long", "float": "double", "str": "char *", "None": "void"}[node.id]
        raise CSourceError("supported annotations: int, bool, float, str, None", node)

    def infer(self, node: ast.expr) -> str:
        if isinstance(node, ast.Constant):
            if isinstance(node.value, str): return "char *"
            if isinstance(node.value, float): return "double"
            return "long long"
        if isinstance(node, ast.Name): return self.scope.get(node.id, "long long")
        if isinstance(node, ast.BinOp):
            return "double" if isinstance(node.op, ast.Div) or "double" in (self.infer(node.left), self.infer(node.right)) else "long long"
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Name):
            if node.func.id == "float": return "double"
            return self.returns.get(node.func.id, "long long")
        return "long long"

    def predeclare(self, body: list[ast.stmt]) -> None:
        found: list[tuple[str, str]] = []
        for statement in body:
            for node in ast.walk(statement):
                name = None
                kind = "long long"
                if isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
                    name, kind = node.targets[0].id, self.infer(node.value)
                elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
                    name, kind = node.target.id, self.annotation(node.annotation)
                elif isinstance(node, ast.For) and isinstance(node.target, ast.Name):
                    name = node.target.id
                if name and name not in self.scope:
                    self.scope[name] = kind
                    found.append((name, kind))
        for name, kind in found:
            self.line(f"{kind} {name};")

    def function(self, node: ast.FunctionDef) -> None:
        if node.decorator_list or node.args.defaults or node.args.vararg or node.args.kwarg or node.args.kwonlyargs:
            raise CSourceError("decorators and advanced parameters are not supported", node)
        previous = self.scope
        self.scope = {}
        params = []
        for arg in node.args.args:
            kind = self.annotation(arg.annotation, "long long")
            self.scope[arg.arg] = kind
            params.append(f"{kind} {arg.arg}")
        result = self.returns[node.name]
        self.line(f"{result} {node.name}({', '.join(params) or 'void'}) {{")
        self.depth += 1
        self.predeclare(node.body)
        for statement in node.body:
            self.statement(statement)
        self.line("return;" if result == "void" else "return 0;")
        self.depth -= 1
        self.line("}")
        self.scope = previous

    def block(self, body: list[ast.stmt]) -> None:
        self.depth += 1
        for statement in body: self.statement(statement)
        self.depth -= 1
        self.line("}")

    def statement(self, node: ast.stmt) -> None:
        if isinstance(node, ast.Pass): self.line(";")
        elif isinstance(node, ast.Expr):
            if isinstance(node.value, ast.Call) and isinstance(node.value.func, ast.Name) and node.value.func.id == "print": self.print_call(node.value)
            else: self.line(self.expr(node.value) + ";")
        elif isinstance(node, (ast.Assign, ast.AnnAssign)):
            target = node.targets[0] if isinstance(node, ast.Assign) and len(node.targets) == 1 else node.target if isinstance(node, ast.AnnAssign) else None
            value = node.value
            if not isinstance(target, ast.Name) or value is None: raise CSourceError("assignment target must be one name", node)
            self.line(f"{target.id} = {self.expr(value)};")
        elif isinstance(node, ast.AugAssign):
            if not isinstance(node.target, ast.Name) or type(node.op) not in self.AUG: raise CSourceError("unsupported augmented assignment", node)
            self.line(f"{node.target.id} {self.AUG[type(node.op)]} {self.expr(node.value)};")
        elif isinstance(node, ast.If):
            self.line(f"if ({self.expr(node.test)}) {{"); self.block(node.body)
            if node.orelse: self.line("else {"); self.block(node.orelse)
        elif isinstance(node, ast.While):
            if node.orelse: raise CSourceError("while-else is not supported", node)
            self.line(f"while ({self.expr(node.test)}) {{"); self.block(node.body)
        elif isinstance(node, ast.For): self.for_loop(node)
        elif isinstance(node, ast.Return): self.line("return;" if node.value is None else f"return {self.expr(node.value)};")
        elif isinstance(node, ast.Break): self.line("break;")
        elif isinstance(node, ast.Continue): self.line("continue;")
        else: raise CSourceError(f"unsupported statement {type(node).__name__}", node)

    def for_loop(self, node: ast.For) -> None:
        if node.orelse or not isinstance(node.target, ast.Name) or not isinstance(node.iter, ast.Call) or not isinstance(node.iter.func, ast.Name) or node.iter.func.id != "range" or node.iter.keywords or not 1 <= len(node.iter.args) <= 3:
            raise CSourceError("only for NAME in range(1-3 arguments) is supported", node)
        args = [self.expr(arg) for arg in node.iter.args]
        start, stop, step = ("0", args[0], "1") if len(args) == 1 else (args[0], args[1], "1") if len(args) == 2 else tuple(args)
        name = node.target.id
        condition = f"({step}) >= 0 ? {name} < ({stop}) : {name} > ({stop})"
        self.line(f"for ({name} = {start}; {condition}; {name} += ({step})) {{")
        self.block(node.body)

    def expr(self, node: ast.expr) -> str:
        if isinstance(node, ast.Constant): return self.constant(node)
        if isinstance(node, ast.Name): return node.id
        if isinstance(node, ast.BinOp):
            left, right = self.expr(node.left), self.expr(node.right)
            if isinstance(node.op, ast.Div): return f"((double)({left}) / (double)({right}))"
            if isinstance(node.op, ast.FloorDiv): return f"floor((double)({left}) / (double)({right}))"
            if isinstance(node.op, ast.Pow): return f"pow({left}, {right})"
            if type(node.op) not in self.BIN: raise CSourceError("unsupported binary operator", node)
            return f"({left} {self.BIN[type(node.op)]} {right})"
        if isinstance(node, ast.UnaryOp):
            op = {ast.USub: "-", ast.UAdd: "+", ast.Not: "!", ast.Invert: "~"}.get(type(node.op))
            if not op: raise CSourceError("unsupported unary operator", node)
            return f"({op}{self.expr(node.operand)})"
        if isinstance(node, ast.BoolOp): return "(" + (" && " if isinstance(node.op, ast.And) else " || ").join(self.expr(x) for x in node.values) + ")"
        if isinstance(node, ast.Compare):
            pieces, left = [], node.left
            for op, right in zip(node.ops, node.comparators):
                if type(op) not in self.CMP: raise CSourceError("unsupported comparison", node)
                pieces.append(f"({self.expr(left)} {self.CMP[type(op)]} {self.expr(right)})"); left = right
            return "(" + " && ".join(pieces) + ")"
        if isinstance(node, ast.IfExp): return f"({self.expr(node.test)} ? {self.expr(node.body)} : {self.expr(node.orelse)})"
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and not node.keywords:
            name = node.func.id
            if name in self.returns or name in {"abs", "pow", "round"}: return f"{name}({', '.join(self.expr(x) for x in node.args)})"
            if name in {"int", "float"} and len(node.args) == 1: return f"(({ 'long long' if name == 'int' else 'double' }){self.expr(node.args[0])})"
            if name == "len" and len(node.args) == 1: return f"strlen({self.expr(node.args[0])})"
        raise CSourceError(f"unsupported expression {type(node).__name__}", node)

    def constant(self, node: ast.Constant) -> str:
        value = node.value
        if value is None: return "0"
        if isinstance(value, bool): return "1" if value else "0"
        if isinstance(value, (int, float)): return repr(value)
        if isinstance(value, str): return '"' + self.escape(value) + '"'
        raise CSourceError(f"unsupported constant {type(value).__name__}", node)

    @staticmethod
    def escape(value: str) -> str:
        return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t")

    def print_call(self, node: ast.Call) -> None:
        if node.keywords: raise CSourceError("print keyword arguments are not supported", node)
        fmt, values = [], []
        for index, arg in enumerate(node.args):
            if index: fmt.append(" ")
            if isinstance(arg, ast.JoinedStr):
                for part in arg.values:
                    if isinstance(part, ast.Constant) and isinstance(part.value, str): fmt.append(self.escape(part.value).replace("%", "%%"))
                    elif isinstance(part, ast.FormattedValue) and part.conversion in {-1, ord("s")} and part.format_spec is None:
                        kind = self.infer(part.value); fmt.append("%s" if kind == "char *" else "%g" if kind == "double" else "%lld"); values.append(self.expr(part.value))
                    else: raise CSourceError("unsupported f-string component", part)
            elif isinstance(arg, ast.Constant) and isinstance(arg.value, str): fmt.append(self.escape(arg.value).replace("%", "%%"))
            else:
                kind = self.infer(arg); fmt.append("%s" if kind == "char *" else "%g" if kind == "double" else "%lld"); values.append(self.expr(arg))
        suffix = ", " + ", ".join(values) if values else ""
        self.line(f"printf(\"{''.join(fmt)}\\n\"{suffix});")
